package:
  name: abseil-cpp
  version: "20240722.0"
  epoch: 0
  description: Abseil Common Libraries (C++)
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - gtest-dev
      - samurai

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/abseil/abseil-cpp
      tag: ${{package.version}}
      expected-commit: 4447c7562e3bc702ade25105912dce503f0c4010

  - runs: |
      cmake -B build -G Ninja \
      -DCMAKE_CXX_STANDARD=17 \
      -DCMAKE_BUILD_TYPE=MinSizeRel \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_INSTALL_LIBDIR=lib \
      -DBUILD_SHARED_LIBS=ON \
      -DABSL_BUILD_TESTING=ON \
      -DABSL_BUILD_TEST_HELPERS=ON \
      -DABSL_USE_EXTERNAL_GOOGLETEST=ON \
      -DABSL_PROPAGATE_CXX_STD=ON \
      -DABSL_FIND_GOOGLETEST=ON
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

data:
  - name: _libs
    items:
      atomic-hook-test-helper:
      bad-any-cast-impl:
      bad-optional-access:
      bad-variant-access:
      base:
      city:
      civil-time:
      cord:
      cord-internal:
      cordz-functions:
      cordz-handle:
      cordz-info:
      cordz-sample-token:
      crc32c:
      crc-cord-state:
      crc-cpu-detect:
      crc-internal:
      debugging-internal:
      demangle-internal:
      die-if-null:
      examine-stack:
      exception-safety-testing:
      exponential-biased:
      failure-signal-handler:
      flags-commandlineflag:
      flags-commandlineflag-internal:
      flags-config:
      flags-internal:
      flags-marshalling:
      flags-parse:
      flags-private-handle-accessor:
      flags-program-name:
      flags-reflection:
      flags-usage:
      flags-usage-internal:
      graphcycles-internal:
      hash:
      hash-generator-testing:
      hashtablez-sampler:
      int128:
      kernel-timeout-internal:
      leak-check:
      log-entry:
      log-flags:
      log-globals:
      log-initialize:
      log-internal-check-op:
      log-internal-conditions:
      log-internal-format:
      log-internal-globals:
      log-internal-log-sink-set:
      log-internal-message:
      log-internal-nullguard:
      log-internal-proto:
      log-internal-test-actions:
      log-internal-test-helpers:
      log-internal-test-matchers:
      log-severity:
      log-sink:
      low-level-hash:
      malloc-internal:
      per-thread-sem-test-common:
      periodic-sampler:
      pow10-helper:
      random-distributions:
      random-internal-distribution-test-util:
      random-internal-platform:
      random-internal-pool-urbg:
      random-internal-randen:
      random-internal-randen-hwaes:
      random-internal-randen-hwaes-impl:
      random-internal-randen-slow:
      random-internal-seed-material:
      random-seed-gen-exception:
      random-seed-sequences:
      raw-hash-set:
      raw-logging-internal:
      scoped-mock-log:
      scoped-set-env:
      spinlock-test-common:
      spinlock-wait:
      stack-consumption:
      stacktrace:
      status:
      statusor:
      str-format-internal:
      strerror:
      string-view:
      strings:
      strings-internal:
      symbolize:
      synchronization:
      test-instance-tracker:
      throw-delegate:
      time:
      time-internal-test-util:
      time-zone:

subpackages:
  - range: _libs
    name: abseil-cpp-${{range.key}}
    description: Abseil Common C++ library
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          libname="${{range.key}}"
          echo "libname: $libname"

          # Replacing hyphens with underscores in libname
          libname_with_underscore="${libname//-/_}"
          echo "libname_with_underscore: $libname_with_underscore"
          ls -latr ${{targets.destdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/libabsl_${libname_with_underscore}.so.* ${{targets.subpkgdir}}/usr/lib/

  - name: abseil-cpp-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - abseil-cpp
    description: abseil-cpp dev

update:
  enabled: true
  github:
    identifier: abseil/abseil-cpp
