package:
  name: amazon-corretto-crypto-provider
  version: 2.4.1
  epoch: 0
  description: |
    The Amazon Corretto Crypto Provider (ACCP) is a collection of high-performance cryptographic implementations exposed via the standard JCA/JCE interfaces.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang-16-extras
      - cmake
      - go
      - openjdk-11

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/corretto/amazon-corretto-crypto-provider
      expected-commit: d7a87faaf130b6aca9194e9603eed710fa81b782
      tag: ${{package.version}}
      recurse-submodules: true

  - runs: |
      export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
      export CFLAGS="-Wno-error=ignored-attributes"
      ./gradlew :spotlessApply
      ./gradlew build -x test

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/java/amazon-corretto-crypto-provider
      mv build/lib/AmazonCorrettoCryptoProvider.jar ${{targets.destdir}}/usr/share/java/amazon-corretto-crypto-provider/AmazonCorrettoCryptoProvider.jar

update:
  enabled: true
  github:
    identifier: corretto/amazon-corretto-crypto-provider
