package:
  name: asciidoc
  version: 10.2.1
  epoch: 0
  description: "Text based documentation"
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - ca-certificates-bundle
      - docbook-xml
      - git
      - libxml2-utils
      - libxslt
      - py3-pip
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/asciidoc-py/asciidoc-py
      tag: ${{package.version}}
      expected-commit: 21e33efe96ba9a51d99d1150691dae750afd6ed1

  - runs: |
      autoreconf -fi

  - uses: autoconf/configure
    with:
      opts: |
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info

  - uses: autoconf/make

  - uses: autoconf/make-install

update:
  enabled: true
  github:
    identifier: asciidoc-py/asciidoc-py
