package:
  name: atlantis
  version: 0.30.0
  epoch: 0
  description: Terraform Pull Request Automation
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - terraform

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - libcap-utils
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/runatlantis/atlantis
      tag: v${{package.version}}
      expected-commit: 03e9e71f92b06cc27335524b8f59feef5a86f217

  - uses: go/build
    with:
      modroot: .
      packages: .
      output: atlantis
      ldflags: -X main.version=${{package.version}} -X main.commit=$(git rev-parse HEAD) -X main.date=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")

  - uses: strip

  # This must come after strip!
  - runs: |
      setcap "cap_net_bind_service=+ep" "${{targets.destdir}}"/usr/bin/atlantis

update:
  enabled: true
  github:
    identifier: runatlantis/atlantis
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        set -euo pipefail
        atlantis version | grep -q "${{package.version}}"
        atlantis --help
