package:
  name: atuin
  version: 18.3.0
  epoch: 2
  description: Magical shell history
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - protobuf-dev
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/atuinsh/atuin
      tag: v${{package.version}}
      expected-commit: 9be49e434e549d6b13928b530139b66fef6171f1

  - uses: rust/cargobump

  - runs: |
      cargo auditable build --locked --release
      cd target/release
      mkdir -p completions
      for sh in 'bash' 'fish' 'zsh'; do
        "./atuin" gen-completions -s "$sh" -o completions/
      done

      install -Dm755 atuin "${{targets.destdir}}"/usr/bin/atuin

      install -Dm 644 "completions/${{package.name}}.bash" "${{targets.destdir}}/usr/share/bash-completion/completions/atuin"
      install -Dm 644 "completions/${{package.name}}.fish" -t "${{targets.destdir}}/usr/share/fish/vendor_completions.d"
      install -Dm 644 "completions/_${{package.name}}" -t "${{targets.destdir}}/usr/share/zsh/site-functions"

  - uses: strip

update:
  enabled: true
  github:
    identifier: atuinsh/atuin
    strip-prefix: v

test:
  environment:
    environment:
      HISTFILE: /root/.bash_history
      ATUIN_SESSION: dummy_session
    contents:
      packages:
        - bash
  pipeline:
    - name: Verify version
      runs: |
        atuin -V
        atuin --version
        atuin --help
    - name: Create a custom Bash history file
      runs: |
        mkdir -p /root
        echo "ls -la" >> /root/.bash_history
        echo "echo Hello, World!" >> /root/.bash_history
    - name: Initialize Atuin database
      runs: |
        atuin init bash
    - name: Import Bash history
      runs: |
        atuin import bash
    - name: List history and check for a known command
      runs: |
        atuin history list | grep "ls -la"
    - name: Search history for a command
      runs: |
        atuin search ls
