package:
  name: bash-default-config
  version: 1.0.0
  epoch: 0
  description: "Bash default configuration"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - bash

environment:
  contents:
    packages:
      - build-base
      - busybox

pipeline:
  - runs: |
      mkdir -p "${{targets.destdir}}"/etc
      cp bashrc "${{targets.contextdir}}"/etc/bash.bashrc

# It is just the config file local in this repo, so we don't need any update
update:
  enabled: false
