package:
  name: c-ares
  version: 1.34.1
  epoch: 0
  description: "an asynchronous DNS resolution library"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - openssf-compiler-options

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/c-ares/c-ares
      tag: v${{package.version}}
      expected-commit: 0c1c60dc60114812eb5950e6b50fa69d923a20e6

  - uses: cmake/configure
    with:
      opts: |
        -DCARES_BUILD_TOOLS=OFF \
        -DCARES_SHARED=ON \
        -DCARES_STATIC=ON \
        -DCARES_SYMBOL_HIDING=ON \
        -DCARES_BUILD_TESTS=OFF

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: "c-ares-dev"
    description: "headers for c-ares"
    pipeline:
      - uses: split/dev
    dependencies:
      provider-priority: 10
      runtime:
        - libev

  - name: "c-ares-doc"
    description: "c-ares documentation"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  github:
    identifier: c-ares/c-ares
    tag-filter-prefix: v
    strip-prefix: v
