package:
  name: cargo-audit
  version: 0.20.1
  epoch: 0
  description: Audit your dependencies for crates with security vulnerabilities reported to the RustSec Advisory Database.
  copyright:
    - license: MIT OR Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cargo-auditable
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rustsec/rustsec
      tag: cargo-audit/v${{package.version}}
      expected-commit: 318ad37b03d9987cd817cdee7bf1d2801bf4d8bc

  - runs: |
      cd cargo-audit
      cargo update --precise 0.3.36 --package time
      cargo auditable build --release
       # Install cargo-audit
      install -Dm755 ../target/release/cargo-audit -t "${{targets.destdir}}"/usr/bin/

  - uses: strip

subpackages:
  - name: cargo-audit-doc
    pipeline:
      - uses: split/manpages
    description: cargo-audit manpages

update:
  enabled: true
  ignore-regex-patterns:
    - 'rustsec'
    - 'platform'
  github:
    identifier: rustsec/rustsec
    use-tag: true
    strip-prefix: cargo-audit/v
    tag-filter-prefix: "cargo-audit/v"

test:
  pipeline:
    - name: Cargo audit binary check
      runs: |
        cargo-audit --version || exit 1
        cargo-audit --help
