package:
  name: chainguard-keys
  version: 2
  epoch: 6
  description: "Chainguard public keys"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox

pipeline:
  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}"/etc/apk/keys
      install -m644 *.pub "${{targets.destdir}}"/etc/apk/keys/

      for i in x86_64 aarch64; do
        mkdir -p "${{targets.destdir}}"/usr/share/apk/keys/${i}
        install -m644 *.pub "${{targets.destdir}}"/usr/share/apk/keys/${i}/
      done

update:
  enabled: false
  exclude-reason: No source to watch for the new versions
