package:
  name: chainguard-security-guide
  version: 0.1.2
  epoch: 1
  description: Security automation content for Chainguard Images
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/stigs
      expected-commit: d26798196d5b8e5d0ab201cc5e7e1dc69f1247db
      tag: v${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share
      cp -r gpos/* ${{targets.destdir}}/usr/share/

  - uses: strip

update:
  enabled: true
  github:
    identifier: chainguard-dev/stigs
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - openscap
  pipeline:
    - name: Verify gpos content is recognized by oscap
      runs: |
        oscap info /usr/share/xml/scap/ssg/content/ssg-chainguard-gpos-ds.xml
