package:
  name: checksec
  version: 2.7.1
  epoch: 0
  description: Binary security checker
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - bash
      - binutils
      - file
      - grep
      - openssl
      - posix-libc-utils

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/slimm609/checksec.sh
      expected-commit: 181cdfa84893a5d72695944efabfa5b56687379c
      tag: ${{package.version}}

  - runs: |
      ./hack/build.sh
      mkdir -p ${{targets.destdir}}/usr/bin
      mv checksec ${{targets.destdir}}/usr/bin/checksec

update:
  enabled: true
  github:
    identifier: slimm609/checksec.sh

test:
  pipeline:
    - runs: |
        checksec --file=/bin/ls --format=csv | grep "Full RELRO,Canary found"
        checksec --version
        checksec --help
