package:
  name: cloudwatch-exporter
  version: 0.16.0 # Check if the version bump in the mvn command is still needed next time this package is updated
  epoch: 0
  description: Metrics exporter for Amazon AWS CloudWatch
  copyright:
    - license: Apache-2.0

# NOTE: JRE runtime dependency required. This is defined in the image which
# allows us to switch out the JDK version.
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - maven
      - openjdk-17
      - openjdk-17-default-jvm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/cloudwatch_exporter
      tag: v${{package.version}}
      expected-commit: 7429de3e3d5e310d9956a0a86cb289d47a8f4c1d

  - uses: maven/pombump

  - runs: |
      mvn package
      ls target/
      mkdir -p ${{targets.destdir}}/usr/share/java/cloudwatch_exporter
      mv target/cloudwatch_exporter-${{package.version}}-jar-with-dependencies.jar  ${{targets.destdir}}/usr/share/java/cloudwatch_exporter/cloudwatch_exporter.jar

update:
  enabled: true
  github:
    tag-filter: v
    identifier: prometheus/cloudwatch_exporter
    strip-prefix: v
    use-tag: true
