package:
  name: crac-criu
  version: 1.4.3
  epoch: 0
  description: A project to implement checkpoint/restore functionality for Linux
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils
      - gnutls-dev
      - iproute2
      - libaio-dev
      - libbpf-dev
      - libbsd-dev
      - libcap-dev
      - libdrm
      - libdrm-dev
      - libnet-dev
      - libnl3
      - libnl3-dev
      - libnl3-static
      - libprotobuf
      - libxml2-utils
      - nftables
      - nftables-dev
      - nftables-static
      - perl
      - pkgconf
      - protobuf-c-dev
      - protobuf-dev
      - protoc

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 352e2c730905bfca240a5e0f3e8085b6c27f606c
      repository: https://github.com/canonical/crac-criu
      tag: ${{package.version}}

  # Remove what isn't used by OpenJDK CRaC
  - uses: patch
    with:
      patches: modify-installation.patch

  - uses: autoconf/make-install
    with:
      opts: PREFIX=/usr

  - uses: strip

update:
  enabled: true
  github:
    identifier: canonical/crac-criu

test:
  pipeline:
    - runs: |
        # check at least if the binary is there in usr/sbin/criu
        if [ ! -f "/usr/sbin/crac-criu" ]; then
          echo "criu binary not found"
          exit 1
        fi
        crac-criu --version
        crac-criu --help
