package:
  name: docker-cli-buildx
  version: 0.17.1
  epoch: 0
  description: buildx is a Docker CLI plugin for extended build capabilities with BuildKit.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/docker/buildx
      tag: v${{package.version}}
      expected-commit: 257815a6fbaee88976808020bf04274388275ae8

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/libexec/docker/cli-plugins/
      make build
      chmod +x bin/build/docker-buildx
      cp bin/build/docker-buildx ${{targets.destdir}}/usr/libexec/docker/cli-plugins/

update:
  enabled: true
  github:
    identifier: docker/buildx
    strip-prefix: v
    tag-filter: v
