package:
  name: docker-selenium
  # Officially they distribute the version with the following format: 4.16.1-20231219
  # But the '-' is not a valid character according to APK versioning spec; and resulting
  # 'package format error' when trying to install the package. The workaround is
  # to replace '-' with '.', then mangling the version to replace back.
  version: 4.25.0.20241010
  epoch: 0
  description: Provides a simple way to run Selenium Grid with Chrome, Firefox, and Edge using Docker, making it easier to perform browser automation
  copyright:
    - license: Apache-2.0
  target-architecture:
    # TODO: Enable aarch64
    # Requires aarch64 variant of Chromedriver
    - x86_64
  dependencies:
    runtime:
      - bash
      - busybox
      - coreutils
      - openjdk-11
      - selenium-server-compat
      - sudo-rs
      - supervisor
      - tzdata

environment:
  contents:
    packages:
      - acl
      - bash
      - build-base
      - busybox
      - bzip2
      - ca-certificates-bundle
      - curl
      - git
      - gnupg
      - jq
      - openjdk-11
      - openjdk-11-default-jvm
      - openjdk-11-jre
      - openssl
      - x11vnc
      - yq
  environment:
    JAVA_HOME: /usr/lib/jvm/java-11-openjdk
    TC: UTC
    SEL_USER: seluser
    SEL_PASSWD: secret

# Transform melange version to replace last dot "." with "-".
var-transforms:
  - from: ${{package.version}}
    match: ^(.+)\.(\d+)$
    replace: $1-$2
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/SeleniumHQ/docker-selenium
      tag: ${{vars.mangled-package-version}}
      expected-commit: 723874729ab63018fc0405490a6f3313ca575ddd

  - uses: patch
    with:
      patches: 0001-fix-paths.patch

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      mkdir -p ${{targets.destdir}}/etc/supervisor/conf.d
      mkdir -p ${{targets.destdir}}/var/tmp

  # https://github.com/SeleniumHQ/docker-selenium/blob/trunk/Base/Dockerfile
  - working-directory: Base
    pipeline:
      - runs: |
          mkdir -p ${{targets.destdir}}/opt/bin
          install -Dm755 check-grid.sh ${{targets.destdir}}/opt/bin/
          install -Dm755 entry_point.sh ${{targets.destdir}}/opt/bin/
          install -Dm755f supervisord.conf ${{targets.destdir}}/etc
          mkdir -p ${{targets.destdir}}/var/run/supervisor
      - runs: |
          mkdir -p ${{targets.destdir}}/opt/selenium
          echo "${SEL_PASSWD}" > ${{targets.destdir}}/opt/selenium/initialPasswd
      # TODO: Implement malware scan for jars retrieved by coursier
      - runs: |
          # Retrieve OpenTelemetry/GRPC Java versions
          export OPENTELEMETRY_VERSION=$(curl "https://api.github.com/repos/open-telemetry/opentelemetry-java/releases/latest" | jq -r ".tag_name" | sed 's/v//')
          export GRPC_VERSION=$(curl "https://api.github.com/repos/grpc/grpc-java/releases/latest" | jq -r ".tag_name" | sed 's/v//')

          mkdir -p ${{targets.destdir}}/external_jars
          curl -sSLfO https://github.com/coursier/launchers/raw/master/coursier
          chmod +x coursier
          # The netty-codec-http bump is for CVE-2024-29025
          ./coursier fetch --classpath --cache ${{targets.destdir}}/external_jars \
            io.opentelemetry:opentelemetry-exporter-otlp:${OPENTELEMETRY_VERSION} \
            io.netty:netty-codec-http:4.1.108.Final \
            io.grpc:grpc-netty:${GRPC_VERSION} > ${{targets.destdir}}/external_jars/.classpath.txt

  - uses: strip

subpackages:
  - name: docker-selenium-supervisor-config
    description: Docker Selenium supervisor configuration
    dependencies:
      replaces:
        - supervisor-config
      provides:
        - supervisor-config
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/etc
          mv ${{targets.destdir}}/etc/supervisord.conf ${{targets.subpkgdir}}/etc
          mv ${{targets.destdir}}/etc/supervisor ${{targets.subpkgdir}}/etc

          # Unset setuid bit
          # jason@ copied this directly from https://serverfault.com/a/238964
          # The extra 0 is to unset the setuid bit apparently.
          chmod 00775 ${{targets.subpkgdir}}/etc/supervisord.conf

  # selenium-hub does not handle rendering or direct interaction with browsers
  # we can skip adding chromium, Xvfb, fluxbox, and related font packages.
  - name: docker-selenium-hub
    description: Docker Selenium Hub
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/opt/bin
          mkdir -p ${{targets.subpkgdir}}/opt/selenium
      # https://github.com/SeleniumHQ/docker-selenium/blob/trunk/Hub/Dockerfile
      - working-directory: Hub
        pipeline:
          - runs: |
              mkdir -p ${{targets.subpkgdir}}/etc/supervisor/conf.d
              cp selenium-grid-hub.conf ${{targets.subpkgdir}}/etc/supervisor/conf.d/
              install -Dm755 start-selenium-grid-hub.sh ${{targets.subpkgdir}}/opt/bin/
              cp example-config.toml ${{targets.subpkgdir}}/opt/selenium/config.toml

  - name: docker-selenium-standalone-chrome
    description: Docker Selenium supervisor configuration
    dependencies:
      runtime:
        - Xvfb
        - chromium
        - chromium-docker-selenium-compat
        - fluxbox
        - font-ipa
        - font-liberation
        - font-misc-cyrillic
        - font-noto-emoji
        - font-ubuntu
        - font-wqy-zenhei
        - fontconfig
        - freetype
        - glib
        - glibc-locale-en
        - libfontconfig1
        - libgcc
        - libnss
        - libnss-tools
        - libxcb
        - mcookie
        - novnc
        - openjdk-11
        - pulseaudio
        - pulseaudio-utils
        - ttf-dejavu
        - websockify
        - x11vnc
        - xauth
        - xkbcomp
        - xkeyboard-config
        - xmessage
        - xvfb-run
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/etc
          mkdir -p ${{targets.subpkgdir}}/opt/bin
      # https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeBase/Dockerfile
      - working-directory: NodeBase
        pipeline:
          - runs: |
              mkdir -p ${{targets.subpkgdir}}/etc/supervisor/conf.d
              mkdir -p ${{targets.subpkgdir}}/usr/share/images/fluxbox
              cp start-selenium-node.sh ${{targets.subpkgdir}}/opt/bin/
              cp start-xvfb.sh ${{targets.subpkgdir}}/opt/bin/
              cp selenium.conf ${{targets.subpkgdir}}/etc/supervisor/conf.d/
              cp start-vnc.sh ${{targets.subpkgdir}}/opt/bin/
              cp start-novnc.sh ${{targets.subpkgdir}}/opt/bin/
              cp selenium_grid_logo.png ${{targets.subpkgdir}}/usr/share/images/fluxbox/ubuntu-light.png
              cp generate_relay_config ${{targets.subpkgdir}}/opt/bin/generate_relay_config

              mkdir -p ${{targets.subpkgdir}}/home/$SEL_USER/.fluxbox
              mkdir -p ${{targets.subpkgdir}}/tmp/.X11-unix
              mkdir -p ${{targets.subpkgdir}}/home/$SEL_USER/.vnc
              mkdir -p ${{targets.subpkgdir}}/opt/selenium
              mkdir -p ${{targets.subpkgdir}}/opt/selenium
              echo "${SEL_PASSWD}" | x11vnc -storepasswd - ${{targets.subpkgdir}}/home/$SEL_USER/.vnc/passwd
      # https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeChrome/Dockerfile
      - working-directory: NodeChrome
        pipeline:
          - runs: |
              cp wrap_chrome_binary ${{targets.subpkgdir}}/opt/bin/wrap_chrome_binary
      # https://github.com/SeleniumHQ/docker-selenium/blob/trunk/Standalone/Dockerfile
      - working-directory: Standalone
        pipeline:
          - runs: |
              cp start-selenium-standalone.sh ${{targets.subpkgdir}}/opt/bin/start-selenium-standalone.sh
              cp selenium.conf ${{targets.subpkgdir}}/etc/supervisor/conf.d/
              cp generate_config ${{targets.subpkgdir}}/opt/bin/generate_config

update:
  enabled: true
  ignore-regex-patterns:
    - '.*grid.*'
  version-transform:
    - match: ^(.+)\-(\d+)$
      replace: $1.$2
  github:
    identifier: SeleniumHQ/docker-selenium
