package:
  name: docker-nginx
  version: 1.27.2
  epoch: 0
  description: NGINX Dockerfiles
  copyright:
    - license: BSD-2-Clause
  dependencies:
    runtime:
      - busybox
      - gettext # templating requires envsubst

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6a4c0cb4ac7e53bbbe473df71b61a5bf9f95252f
      repository: https://github.com/nginxinc/docker-nginx
      tag: ${{package.version}}

  - runs: |
      mkdir -p "${{targets.contextdir}}/docker-entrypoint.d/"
      cp entrypoint/20-envsubst-on-templates.sh "${{targets.contextdir}}/docker-entrypoint.d/"
      cp entrypoint/docker-entrypoint.sh "${{targets.contextdir}}/docker-entrypoint.sh"

update:
  enabled: true
  github:
    identifier: nginxinc/docker-nginx
    use-tag: true

test:
  pipeline:
    - name: "Check expected scripts exist"
      runs: |
        stat /docker-entrypoint.d/20-envsubst-on-templates.sh
        stat /docker-entrypoint.sh
