package:
  name: double-conversion
  version: 3.3.0
  epoch: 1
  description: "Efficient binary-decimal and decimal-binary conversion routines for IEEE doubles"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - openssf-compiler-options

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/google/double-conversion
      tag: v${{package.version}}
      expected-commit: 4f7a25d8ced8c7cf6eee6fd09d6788eaa23c9afe

  - uses: cmake/configure
    with:
      opts: -DBUILD_SHARED_LIBS=ON

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: "Efficient binary-decimal and decimal-binary conversion routines for IEEE doubles - development headers"
    pipeline:
      - uses: split/dev

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-dev
        - build-base
  pipeline:
    - runs: |
        # Compile test
        g++ test.cpp -o test -ldouble-conversion

        # Run test
        if ./test; then
          rm ./test && echo "Test Passed!" && exit 0
        else
          rm ./test && echo "Test Failed!" && exit 1
        fi

update:
  enabled: true
  github:
    identifier: google/double-conversion
    strip-prefix: v
