#nolint:valid-pipeline-git-checkout-commit,valid-pipeline-git-checkout-tag
package:
  name: fluent-plugin-newrelic
  version: "1.2.2_git20230928"
  epoch: 3
  description: Sends FluentD events to New Relic
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby3.2-fluentd

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - runs: |
      git clone https://github.com/newrelic/newrelic-fluentd-output
      cd newrelic-fluentd-output
      git checkout c08367bfae3b019a84d43a00a9db065d12033266

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
      dir: newrelic-fluentd-output

  - uses: ruby/install
    with:
      # Hard-coding because of difference in gemspec file name and gem name
      gem: fluent-plugin-newrelic
      # Hard-coding the version here to match with gemspec till they come with a release/tag
      version: 1.2.2
      dir: newrelic-fluentd-output

  - uses: ruby/clean

vars:
  gem: newrelic-fluentd-output

update:
  enabled: false
