package:
  name: fluent-plugin-label-router
  version: "0.2.10_git20230928"
  epoch: 5
  description: Label-Router helps routing log messages based on their labels and namespace tag in a Kubernetes environment.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby3.2-fluentd
      - ruby3.2-prometheus-client

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  # Hack until they cut a release
  - runs: |
      git clone https://github.com/kube-logging/fluent-plugin-label-router
      cd fluent-plugin-label-router
      git checkout 695d289f3b170d4739e79b21ce062700b10acf16

  - working-directory: fluent-plugin-label-router
    pipeline:
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          # Hard-coding the version here to match with gemspec till they come with a release/tag
          version: 0.2.10
      - uses: ruby/clean

vars:
  gem: fluent-plugin-label-router

update:
  enabled: false
