package:
  name: fluent-plugin-prometheus
  version: 2.2.0
  epoch: 0
  description: A fluent plugin that collects metrics and exposes for Prometheus.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - ruby3.2-fluent-plugin-prometheus=${{package.version}}-r${{package.epoch}}
    runtime:
      - ruby3.2-fluentd
      - ruby3.2-prometheus-client

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: fluent-plugin-prometheus

pipeline:
  - uses: git-checkout
    with:
      destination: ${{vars.gem}}
      expected-commit: d2dc295fe08a9d3ad665d90081819793de01a4a5
      repository: https://github.com/fluent/fluent-plugin-prometheus
      tag: v${{package.version}}

  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: ruby/unlock-spec
      - uses: ruby/build
        with:
          gem: ${{package.name}}
      - uses: ruby/install
        with:
          gem: ${{package.name}}
          version: ${{package.version}}
      - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: fluent/fluent-plugin-prometheus
    strip-prefix: v
    use-tag: true
