package:
  name: gdal
  version: 3.9.3
  epoch: 0
  description: GDAL is an open source MIT licensed translator library for raster and vector geospatial data formats.
  copyright:
    - license: MIT

environment:
  environment:
    GDAL_PYTHON_BINDINGS_WITHOUT_NUMPY: "YES"
  contents:
    packages:
      - armadillo-dev
      - arpack-dev
      - autoconf
      - automake
      - basisu-dev
      - bison
      - blosc-dev
      - brunsli-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - curl-dev
      - expat-dev
      - geos-dev
      - glibc-iconv
      - lerc-dev
      - libdeflate-dev
      - libgeotiff-dev
      - libpng-dev
      - libtirpc-dev
      - libxml2-dev
      - mariadb-dev
      - nlohmann-json
      - odbc-cpp-wrapper-dev
      - openblas-dev
      - opencl-dev
      - openjpeg-dev
      - openssf-compiler-options
      - openssl-dev
      - pcre2-dev
      - proj-dev
      - py3-setuptools
      - python3
      - python3-dev
      - qhull-dev
      - sqlite-dev
      - swig
      - tiff-dev
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: f293d8ccc6b98f617db88f8593eae37f7e4b32d49a615b2cba5ced12c7bebdae
      uri: https://github.com/OSGeo/gdal/releases/download/v${{package.version}}/gdal-${{package.version}}.tar.gz

  # Preffer gdal's FindZSTD which chooses shared linking, rather than
  # zstd-dev newly shipped cmake module. This preserves shared linking
  # against zstd, like it was done by gdal prior to merge of zstd-dev
  # and zstd-cmake.
  - runs: |
      rm -rf /usr/lib/cmake/zstd

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: gdal-dev
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - runs: |
            gdal-config --version
        - uses: test/pkgconf

  - name: py3-gdal
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/
          mv ${{targets.destdir}}/usr/lib/python3* ${{targets.subpkgdir}}/usr/lib/

  - name: gdal-tools
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/bin/* ${{targets.subpkgdir}}/usr/bin/
          chmod a+x scripts/*
          mv scripts/* ${{targets.subpkgdir}}/usr/bin/
    test:
      pipeline:
        - runs: |
            detect_printf.sh --version
            detect_printf.sh --help
            detect_self_assignment.sh --version
            detect_self_assignment.sh --help
            detect_suspicious_char_digit_zero.sh --version
            detect_suspicious_char_digit_zero.sh --help
            detect_tabulations.sh --version
            detect_tabulations.sh --help
            gdal-bash-completion.sh --version
            gdal-bash-completion.sh --help
            gdal_contour --help
            gdal_create --version
            gdal_create --help
            gdal_footprint --version
            gdal_footprint --help
            gdal_grid --version
            gdal_grid --help
            gdal_rasterize --version
            gdal_rasterize --help
            gdal_translate --version
            gdal_translate --help
            gdal_viewshed --version
            gdal_viewshed --help
            gdaladdo --version
            gdaladdo --help
            gdalbuildvrt --version
            gdalbuildvrt --help
            gdaldem --help
            gdalenhance --version
            gdalinfo --version
            gdalinfo --help
            gdallocationinfo --version
            gdalmanage --version
            gdalmanage --help
            gdalmdiminfo --version
            gdalmdiminfo --help
            gdalmdimtranslate --version
            gdalmdimtranslate --help
            gdalsrsinfo --version
            gdalsrsinfo --help
            gdaltindex --version
            gdaltindex --help
            gdaltransform --version
            gdaltransform --help
            gdalwarp --version
            gdalwarp --help
            gnmanalyse --version
            gnmmanage --version
            nearblack --version
            nearblack --help
            ogr2ogr --version
            ogr2ogr --help
            ogrinfo --version
            ogrinfo --help
            ogrlineref --version
            ogrtindex --help
            setdevenv.sh --version
            setdevenv.sh --help
            sozip --version
            sozip --help

update:
  enabled: true
  release-monitor:
    identifier: 881
