package:
  name: graphicsmagick
  version: "1.3.43"
  epoch: 1
  description: GraphicsMagick Image Processing Syste,
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - freetype-dev
      - libltdl
      - libpng-dev
      - libtool
      - libwebp-dev
      - libxml2-dev
      - mercurial
      - tiff-dev

pipeline:
  - runs: |
      # Clone the repository, we need to manually update the below commit with every latest release.
      # hg clone http://hg.code.sf.net/p/graphicsmagick/code -r ${LATEST_COMMIT}"
      # Fetching commit instead of tar.gz, for security.
      hg clone http://hg.code.sf.net/p/graphicsmagick/code graphicsmagick -r eff5b40bc7702651ceffbe0eeb26d5cd278abf95

  - uses: autoconf/configure
    with:
      dir: graphicsmagick
      opts: |
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --localstatedir=/var \
        --disable-openmp \
        --disable-static \
        --enable-shared \
        --with-gs-font-dir=/usr/share/fonts/Type1 \
        --with-modules \
        --with-perl \
        --with-quantum-depth=16 \
        --with-threads \
        --with-ttf \
        --with-webp

  - uses: autoconf/make
    with:
      dir: graphicsmagick

  - uses: autoconf/make-install
    with:
      dir: graphicsmagick

  - uses: strip

subpackages:
  - name: graphicsmagick-doc
    pipeline:
      - uses: split/manpages

  - name: graphicsmagick-cpp
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/libGraphicsMagick++.* ${{targets.subpkgdir}}/usr/lib/

  - name: graphicsmagick-dev
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - runs: |
            GraphicsMagick++-config --version
            GraphicsMagick-config --version
            GraphicsMagickWand-config --version
        - uses: test/pkgconf

update:
  enabled: true
  manual: true
  release-monitor:
    identifier: 1248

test:
  pipeline:
    - runs: |
        gm help
        gm version | grep ${{package.version}}
