package:
  name: gst-plugins-base
  version: 1.24.8
  epoch: 0
  description: GStreamer streaming media framework base plug-ins
  copyright:
    - license: GPL-2.0-or-later AND LGPL-2.0-or-later

environment:
  contents:
    packages:
      - alsa-lib-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cdparanoia-dev
      - cmake
      - expat-dev
      - gdk-pixbuf
      - glib-dev
      - glib-gir
      - gobject-introspection-dev
      - graphene-dev
      - gstreamer
      - gstreamer-dev
      - gtk-3-dev
      - libdrm-dev
      - libice-dev
      - libogg-dev
      - libsm-dev
      - libtheora-dev
      - libvorbis-dev
      - libxv-dev
      - mesa-dev
      - mesa-egl
      - mesa-gbm
      - mesa-gl
      - mesa-glapi
      - mesa-gles
      - mesa-libgallium
      - meson
      - opus-dev
      - orc-compiler
      - orc-dev
      - perl

pipeline:
  - uses: fetch
    with:
      expected-sha512: ae4ae070fd20e01f422b36e1c943fc24fc41668706f4150c1d596673b0f11e001a5786cec9b5328b90759cc5da421522a499255a6fd6c52ba48eb77e4c37a50c
      uri: https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-${{package.version}}.tar.xz

  - uses: meson/configure
    with:
      opts: |
        -Dalsa=enabled \
        -Dintrospection=enabled \
        -Dgl=enabled \
        -Dgl-graphene=enabled \
        -Dgl-jpeg=enabled \
        -Dgl-png=enabled \
        -Dtests=disabled \

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
    description: ${{package.name}} dev

  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/manpages
    description: ${{package.name}} manpages

  - name: ${{package.name}}-lang
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share/locale
          mv ${{targets.destdir}}/usr/share/locale ${{targets.subpkgdir}}/usr/share/locale
    description: ${{package.name}} lang

update:
  enabled: true
  release-monitor:
    identifier: 21850

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        gst-device-monitor-1.0 --version
        gst-discoverer-1.0 --help
        gst-play-1.0 --version
        gst-device-monitor-1.0 --help
        gst-discoverer-1.0 version
        gst-play-1.0 --help
