package:
  name: isa-l
  version: "2.31.0"
  epoch: 0
  description: "Intelligent Storage Acceleration Library"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - libtool
      - nasm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/intel/isa-l
      tag: v${{package.version}}
      expected-commit: bd226375027899087bd48f3e59b910430615cc0a

  - runs: ./autogen.sh

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: isa-l-dev
    pipeline:
      - uses: split/dev

  - name: isa-l-doc
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  github:
    identifier: intel/isa-l
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - gzip
        - kubectl-latest # Just to have a large binary to compress.
  pipeline:
    - name: Verify igzip installation
      runs: |
        igzip -h
        igzip --version
        igzip --help
    - name: Compare igzip to gzip
      runs: |
        time igzip -3 -n < $(which kubectl) > igzip.gz
        time gzip -n < $(which kubectl) > gzip.gz
        ls -al
    - name: Compare igzip to gunzip
      runs: |
        # Make sure both can decompress the output of the other.
        time igzip --rm -d gzip.gz
        time gunzip igzip.gz
        ls -al
    - name: Compare contents
      runs: |
        diff -q igzip gzip
