package:
  name: k6
  version: 0.54.0
  epoch: 0
  description: A modern load testing tool, using Go and JavaScript
  copyright:
    - license: AGPL-3.0-or-later

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grafana/k6
      tag: v${{package.version}}
      expected-commit: baba871c8a760352290f0402cd421b79f2a3e948

  - uses: go/build
    with:
      packages: .
      output: k6

  - uses: strip

update:
  enabled: true
  github:
    identifier: grafana/k6
    strip-prefix: v

test:
  pipeline:
    - name: "test out k6 version"
      runs: |
        k6 version
        k6 --version
        k6 --help
    - name: "run a demo test"
      runs: |
        k6 new
        k6 run script.js --duration=1.5s
