package:
  name: kaniko
  version: 1.23.2
  epoch: 3
  description: Build Container Images In Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/GoogleContainerTools/kaniko
      tag: v${{package.version}}
      expected-commit: 1ae9a8416c14418625de90c1115052c0a6ebee07

  - uses: go/bump
    with:
      deps: github.com/opencontainers/runc@v1.1.12 google.golang.org/grpc@v1.64.1
      tidy: false

  - uses: go/build
    with:
      output: executor
      packages: ./cmd/executor
      ldflags: -X github.com/GoogleContainerTools/kaniko/pkg/version.Version=v${{package.version}}

subpackages:
  - name: kaniko-warmer
    pipeline:
      - uses: go/build
        with:
          output: warmer
          packages: ./cmd/warmer
          ldflags: -X github.com/GoogleContainerTools/kaniko/pkg/version.Version=v${{package.version}}
    test:
      pipeline:
        - runs: |
            warmer --help

  - name: kaniko-compat
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /kaniko/
          mkdir -p ${{targets.subpkgdir}}/kaniko/
          ln -sf /usr/bin/executor ${{targets.subpkgdir}}/kaniko/
    dependencies:
      runtime:
        - kaniko

  - name: kaniko-warmer-compat
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /kaniko/
          mkdir -p ${{targets.subpkgdir}}/kaniko/
          ln -sf /usr/bin/warmer ${{targets.subpkgdir}}/kaniko/
    dependencies:
      runtime:
        - kaniko-warmer

update:
  enabled: true
  github:
    identifier: GoogleContainerTools/kaniko
    strip-prefix: v
    use-tag: true
    tag-filter: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        executor --help
        executor version
