package:
  name: kubernetes-replicator
  version: 2.10.2
  epoch: 0
  description: Kubernetes controller for synchronizing secrets & config maps across namespaces
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mittwald/kubernetes-replicator
      tag: v${{package.version}}
      expected-commit: 8f4de965a57b974b446fae30048269894fd4ff3d

  - uses: go/build
    with:
      packages: .
      output: kubernetes-replicator

update:
  enabled: true
  github:
    identifier: mittwald/kubernetes-replicator
    strip-prefix: v

test:
  pipeline:
    - runs: |
        set -x
        # Confirm the build was successful with a smoke test to check that 'Usage of kubernetes-replicator' string
        # is present in --help output
        kubernetes-replicator --help 2>&1 | grep "Usage of kubernetes-replicator:"
