package:
  name: kubernetes-csi-livenessprobe
  version: 2.14.0
  epoch: 2
  description: A sidecar container that can be included in a CSI plugin pod to enable integration with Kubernetes Liveness Probe.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-csi/livenessprobe
      tag: v${{package.version}}
      expected-commit: 008a7b152f086b6c82f2a17c2a734d27614da673

  - uses: go/build
    with:
      packages: ./cmd/livenessprobe
      ldflags: "-w -X main.version=v${{package.version}} -extldflags '-static'"
      output: livenessprobe

update:
  enabled: true
  github:
    identifier: kubernetes-csi/livenessprobe
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - curl
        - kubernetes-csi-driver-hostpath
  pipeline:
    - uses: test/kwok/cluster
    - runs: |
        mkdir -p /csi
        hostpathplugin --v=5 --endpoint="unix:///csi/csi.sock" --nodeid="node-000000" & sleep 5
        livenessprobe --csi-address /csi/csi.sock --health-port 8080 & sleep 10
        curl -Lk localhost:8080/healthz
