package:
  name: libice
  version: 1.1.1
  epoch: 3
  description: X11 Inter-Client Exchange library
  copyright:
    - license: X11

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - check-dev
      - libtool
      - pkgconf-dev
      - util-macros
      - xmlto
      - xorgproto
      - xtrans

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.freedesktop.org/xorg/lib/libice.git
      tag: libICE-${{package.version}}
      expected-commit: be1888a46e446dfcaa62ac0a97d96bb77b6816d4

  - runs: |
      ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --enable-ipv6 \
        --enable-docs \
        --with-xmlto \
        --without-fop

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libice-static
    description: libice static library
    pipeline:
      - uses: split/static

  - name: libice-doc
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/share"
          mv "${{targets.destdir}}/usr/share/doc" "${{targets.subpkgdir}}/usr/share"
    description: libice manpages

  - name: libice-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libice
    description: libice dev

update:
  enabled: true
  release-monitor:
    identifier: 1638
