package:
  name: libmilter
  version: 1.0.3
  epoch: 0
  description: Sendmail Mail Filter API (Milter)
  copyright:
    - license: Sendmail

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - linux-headers
      - m4

pipeline:
  - uses: fetch
    with:
      expected-sha256: 90f5ae74c35a84808861933ba094201b901b70c6b2903684dcf39bdae8a5a1a2
      uri: https://ftp.sendmail.org/sendmail.8.17.2.tar.gz

  - runs: |
      make -C libmilter MILTER_SOVER=${{package.version}}

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/lib
      make -C libmilter \
        INCOWN=root INCGRP=root INCMODE=644 \
        LIBOWN=root LIBGRP=root LIBMODE=644 UBINMODE=755 \
        MILTER_SOVER=${{package.version}} \
        DESTDIR="${{targets.destdir}}" \
        install

  - uses: strip

subpackages:
  - name: libmilter-dev
    pipeline:
      - uses: split/dev
    description: libmilter dev

update:
  enabled: true
  manual: true # the library we fetch uses a different version to the melange package.version
  release-monitor:
    identifier: 4796
