package:
  name: libmodbus
  version: 3.1.10
  epoch: 0
  description: Modbus library which supports RTU communication over a serial line or a TCP link
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - linux-headers

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/stephane/libmodbus
      expected-commit: 2cbafa3113e276c3697d297f68e88d112b53174d
      tag: v${{package.version}}

  - runs: ./autogen.sh

  - runs: libtoolize --force && aclocal && autoconf --force && automake --add-missing

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libmodbus-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libmodbus
    description: libmodbus dev

  - name: libmodbus-doc
    pipeline:
      - uses: split/manpages
    description: libmodbus manpages

update:
  enabled: true
  github:
    identifier: stephane/libmodbus
    strip-prefix: v
