package:
  name: libnetfilter_queue
  version: "1.0.5"
  epoch: 4
  description: API to packets that have been queued by the kernel packet filter
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - libmnl-dev
      - libnfnetlink-dev
      - libtool
      - pkgconf-dev

pipeline:
  - uses: git-checkout
    with:
      repository: git://git.netfilter.org/libnetfilter_queue
      tag: libnetfilter_queue-${{package.version}}
      expected-commit: 659b457fc395f6560c73316e31699ca41b4c0d2e

  - runs: |
      ./autogen.sh

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

subpackages:
  - name: libnetfilter_queue-dev
    description: libnetfilter_queue development files
    pipeline:
      - uses: split/dev

update:
  enabled: true
  release-monitor:
    identifier: 1679
