package:
  name: libnspr
  version: "4.35"
  epoch: 3
  description: "Netscape Portable Runtime (NSPR) provides a platform-neutral API for system level and libc-like functions."
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - mercurial

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.mozilla.org/pub/mozilla.org/nspr/releases/v${{package.version}}/src/nspr-${{package.version}}.tar.gz
      expected-sha256: 7ea3297ea5969b5d25a5dd8d47f2443cda88e9ee746301f6e1e1426f8a6abc8f

  - uses: autoconf/configure
    with:
      dir: nspr
      opts: |
        --enable-64bit \
        --host=${{host.triplet.gnu}} \
        --target=${{host.triplet.gnu}} \
        --enable-optimize \
        --disable-debug \
        --prefix=/usr

  - uses: autoconf/make
    with:
      dir: nspr

  - uses: autoconf/make-install
    with:
      dir: nspr

  # Cleanup leftovers from the build.
  - runs: |
      rm -r "${{targets.destdir}}"/usr/include/nspr/md
      rm -r "${{targets.destdir}}"/usr/bin/compile-et.pl
      rm -r "${{targets.destdir}}"/usr/bin/prerr.properties

  # Link the NSPR package config file into the right place.
  - working-directory: nspr
    runs: |
      mkdir -p "${{targets.destdir}}/usr/lib/pkgconfig/"
      ln -s nspr.pc "${{targets.destdir}}/usr/lib/pkgconfig/mozilla-nspr.pc"

  - uses: strip

subpackages:
  - name: libnspr-dev
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - runs: |
            nspr-config --version

update:
  enabled: true
  release-monitor:
    identifier: 7953
