package:
  name: libslirp
  version: 4.8.0
  epoch: 0
  description: A general purpose TCP-IP emulator
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - glib-dev
      - meson

pipeline:
  - uses: fetch
    with:
      uri: https://gitlab.freedesktop.org/slirp/libslirp/-/archive/v${{package.version}}/libslirp-v${{package.version}}.tar.gz
      expected-sha512: eef9d77f1588c4e3dcf91cd53e54db235d624998fc64df75d389657411635f28bfcbe0c81cd3b0ede7792eea1eb7ef716b8a87a199a6be1e9a29da27ca4a1df4

  - uses: meson/configure

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

subpackages:
  - name: libslirp-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libslirp
    description: libslirp dev

update:
  enabled: true
  release-monitor:
    identifier: 96796
