package:
  name: libssh2
  version: 1.11.0 # Remove CVE-2023-48795.patch when upgrading to 1.11.1
  epoch: 4
  description: "A library implementing the SSH2 protocol as defined by Internet Drafts"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - openssl-dev
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/libssh2/libssh2.git
      tag: libssh2-${{package.version}}
      expected-commit: 1c3f1b7da588f2652260285529ec3c1f1125eb4e

  - uses: patch
    with:
      # Source CVE-2023-48795: https://github.com/libssh2/libssh2/commit/d34d9258b8420b19ec3f97b4cc5bf7aa7d98e35a
      patches: CVE-2023-48795.patch

  - runs: autoreconf -vfi

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "libssh2-dev"
    description: "headers for libssh2"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  ignore-regex-patterns:
    - "^RELEASE.*"
    - "^beforenb.*"
    - "^start$"
  github:
    identifier: libssh2/libssh2
    strip-prefix: libssh2-
