package:
  name: libsm
  version: 1.2.4
  epoch: 4
  description: X11 Session Management library
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - gettext-dev
      - intltool
      - libice-dev
      - libtool
      - libuuid
      - pkgconf-dev
      - util-linux-dev
      - util-macros
      - xmlto
      - xorgproto
      - xtrans

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.freedesktop.org/xorg/lib/libsm.git
      tag: libSM-${{package.version}}
      expected-commit: dc882ac7b748048f12b033d0d8e5267a6e36036a

  - runs: autoreconf -vfi

  - uses: autoconf/configure
    with:
      opts: |
        --enable-docs \
        --with-xmlto \
        --without-fop \
        --with-libuuid

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libsm-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libsm
        - util-linux-dev
    description: libsm dev

  - name: libsm-doc
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/share"
          mv "${{targets.destdir}}/usr/share/doc" "${{targets.subpkgdir}}/usr/share"
    description: libsm manpages

update:
  enabled: true
  release-monitor:
    identifier: 1726
