package:
  name: libtirpc
  version: 1.3.5
  epoch: 0
  description: Transport Independent RPC library (SunRPC replacement)
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - krb5-dev
      - libtool

pipeline:
  - uses: fetch
    with:
      expected-sha256: 9b31370e5a38d3391bf37edfa22498e28fe2142467ae6be7a17c9068ec0bf12f
      uri: https://downloads.sourceforge.net/project/libtirpc/libtirpc/${{package.version}}/libtirpc-${{package.version}}.tar.bz2

  - uses: autoconf/configure
    with:
      opts: |
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \
        --prefix=/usr \
        --sysconf=/etc

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libtirpc-static
    pipeline:
      - uses: split/static
    description: libtirpc static

  - name: libtirpc-doc
    pipeline:
      - uses: split/manpages
    description: libtirpc manpages

  - name: libtirpc-conf
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/etc
          mv ${{targets.destdir}}/etc/* ${{targets.subpkgdir}}/etc/
    description: Configuration files for TI-RPC

  - name: libtirpc-nokrb
    pipeline:
      - uses: autoconf/configure
        with:
          opts: |
            --host=${{host.triplet.gnu}} \
            --build=${{host.triplet.gnu}} \
            --prefix=/usr \
            --sysconf=/etc \
            --disable-gssapi \
            SONAME_SUFFIX='-nokrb'
      - uses: autoconf/make
      - runs: make install DESTDIR=${{targets.subpkgdir}}
      - uses: strip
    description: Transport Independent RPC library (SunRPC replacement) - without GSS-API/Kerberos

  - name: libtirpc-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libtirpc
        - krb5-dev
        - libtirpc-conf
    description: libtirpc dev

update:
  enabled: true
  release-monitor:
    identifier: 1740
