package:
  name: libusb
  version: 1.0.27
  epoch: 0
  description: Library that enables userspace access to USB devices
  copyright:
    - license: LGPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libatomic
      - linux-headers

pipeline:
  - uses: fetch
    with:
      expected-sha256: ffaa41d741a8a3bee244ac8e54a72ea05bf2879663c098c82fc5757853441575
      uri: https://github.com/libusb/libusb/releases/download/v${{package.version}}/libusb-${{package.version}}.tar.bz2

  - uses: autoconf/configure
    with:
      opts: |
        --disable-udev \
        --enable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libusb-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libusb
    description: libusb dev
    test:
      pipeline:
        - uses: test/pkgconf

update:
  enabled: true
  release-monitor:
    identifier: 1749
