package:
  name: libx11
  version: 1.8.10
  epoch: 0
  description: X11 client-side library
  copyright:
    - license: XFree86-1.1

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - gtk-doc
      - intltool
      - libtool
      - libxcb-dev
      - pkgconf-dev
      - util-macros
      - xmlto
      - xorgproto
      - xtrans

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.freedesktop.org/xorg/lib/libx11.git
      tag: libX11-${{package.version}}
      expected-commit: ed9fb5535efe1e5278654b6b3994a34337b4bf1a

  - runs: ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --with-xcb \
        --disable-thread-safety-constructor

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libx11-static
    description: libx11 static library
    pipeline:
      - uses: split/static

  - name: libx11-doc
    pipeline:
      - uses: split/manpages
    description: libx11 manpages

  - name: libx11-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libx11
        - libxcb-dev
        - xtrans
    description: libx11 dev
    test:
      pipeline:
        - uses: test/pkgconf

update:
  enabled: true
  release-monitor:
    identifier: 1764
