package:
  name: libxt
  version: 1.3.0
  epoch: 2
  description: X11 toolkit intrinsics library
  copyright:
    - license: MIT-open-group

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libice-dev
      - libsm-dev
      - libtool
      - libx11-dev
      - pkgconf-dev
      - util-macros
      - xorgproto

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.freedesktop.org/xorg/lib/libxt.git
      tag: libXt-${{package.version}}
      expected-commit: 64fca6a2d7cf4fee28ca2277ca6a8b7b32aee66e

  - runs: ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: --disable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libxt-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libxt
        - libsm-dev
    description: libxt dev

  - name: libxt-doc
    pipeline:
      - uses: split/manpages
    description: libxt manpages

update:
  enabled: true
  release-monitor:
    identifier: 1793
