package:
  name: libxdmcp
  version: 1.1.5
  epoch: 3
  description: X11 Display Manager Control Protocol library
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libbsd-dev
      - libtool
      - pkgconf-dev
      - util-macros
      - xmlto
      - xorgproto

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.freedesktop.org/xorg/lib/libxdmcp.git
      tag: libXdmcp-${{package.version}}
      expected-commit: 1192d3bc407348ff316bd3bffc791b3ac73f591b

  - runs: ./autogen.sh

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libxdmcp-doc
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/share"
          mv "${{targets.destdir}}/usr/share/doc" "${{targets.subpkgdir}}/usr/share"
    description: libxdmcp manpages

  - name: libxdmcp-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libxdmcp
    description: libxdmcp dev

update:
  enabled: true
  release-monitor:
    identifier: 1772
