package:
  name: libxrender
  version: 0.9.11
  epoch: 7
  description: X Rendering Extension client library
  copyright:
    - license: XFree86-1.1

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - libx11-dev
      - pkgconf-dev
      - util-macros
      - xorgproto

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.freedesktop.org/xorg/lib/libxrender.git
      tag: libXrender-${{package.version}}
      expected-commit: e5e23272394c90731debd7e18dd167e8c25b5c15

  - runs: ./autogen.sh

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libxrender-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libxrender
    description: libxrender dev

  - name: libxrender-doc
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/share"
          mv "${{targets.destdir}}/usr/share/doc" "${{targets.subpkgdir}}/usr/share"
    description: libxrender manpages

update:
  enabled: true
  release-monitor:
    identifier: 1789
