package:
  name: libxcomposite
  version: 0.4.6
  epoch: 3
  description: X11 Composite extension library
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - libx11-dev
      - libxext-dev
      - libxfixes-dev
      - pkgconf-dev
      - util-macros
      - xorgproto

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.freedesktop.org/xorg/lib/libxcomposite.git
      tag: libXcomposite-${{package.version}}
      expected-commit: cecff847395deb553b6331f31776f9cbfc809add

  - runs: ./autogen.sh

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libxcomposite-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libxext-dev
    description: libxcomposite dev

  - name: libxcomposite-doc
    pipeline:
      - uses: split/manpages
    description: libxcomposite manpages

update:
  enabled: true
  release-monitor:
    identifier: 1769
