package:
  name: libxcvt
  version: 0.1.2
  epoch: 0
  description: "VESA CVT standard timing modeline generation library & utility"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - meson

pipeline:
  - uses: fetch
    with:
      uri: https://www.x.org/releases/individual/lib/libxcvt-${{package.version}}.tar.xz
      expected-sha256: 0561690544796e25cfbd71806ba1b0d797ffe464e9796411123e79450f71db38

  - uses: meson/configure

  - uses: meson/compile

  - uses: meson/install

subpackages:
  - name: libxcvt-dev
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/pkgconf

  - name: libxcvt-doc
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  release-monitor:
    identifier: 235147
