package:
  name: llvm-cmake-19
  version: 19.1.2
  epoch: 0
  description: CMake macros for LLVM build system, version 19
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - cmake

environment:
  contents:
    packages:
      - busybox
      - openssf-compiler-options

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+).*
    replace: $1
    to: major-version

pipeline:
  - working-directory: ${{targets.destdir}}/usr/lib/llvm-${{vars.major-version}}/share/cmake
    uses: fetch
    with:
      uri: https://github.com/llvm/llvm-project/releases/download/llvmorg-${{package.version}}/cmake-${{package.version}}.src.tar.xz
      expected-sha256: 139209d798fbe4a84becfa605aee7fd8f4412c6591976f3e672211e3fbdcf65b
      delete: true

update:
  enabled: true
  github:
    identifier: llvm/llvm-project
    strip-prefix: llvmorg-
    tag-filter: llvmorg-19.1
    use-tag: true
