package:
  name: lua-lpeg
  version: 1.1.0
  epoch: 1
  description: "Pattern-matching library for Lua"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - luajit-dev

pipeline:
  - uses: fetch
    with:
      uri: https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-${{package.version}}.tar.gz
      expected-sha256: 4b155d67d2246c1ffa7ad7bc466c1ea899bbc40fef0257cc9c03cecbaed4352a

  - runs: |
      make LUADIR=/usr/include/lua

  - runs: |
      install -Dm755 lpeg.so \
        ${{targets.destdir}}/usr/lib/lua/lpeg.so
      install -Dm644 re.lua \
        ${{targets.destdir}}/usr/share/lua/re.lua

      rockdir=${{targets.destdir}}/usr/lib/luarocks/rocks-common/lpeg/${{package.version}}
      mkdir -p $rockdir
      echo "rock_manifest = {}" > "$rockdir"/rock_manifest

subpackages:
  - name: lua5.1-lpeg
    description: "Pattern-matching library for Lua 5.1"
    dependencies:
      runtime:
        - luajit # use luajit in place of lua5.1
      provides:
        - lua-lpeg # placeholder if/when we ever rebuild this for more versions of lua
    pipeline:
      - runs: |
          install -Dm755 lpeg.so \
            ${{targets.contextdir}}/usr/lib/lua/5.1/lpeg.so
          install -Dm644 re.lua \
            ${{targets.contextdir}}/usr/share/lua/5.1/re.lua

update:
  enabled: true
  release-monitor:
    identifier: 1852
