package:
  name: memtier-benchmark
  version: 2.1.1
  epoch: 0
  description: "NoSQL Redis and Memcache traffic generation and benchmarking tool."
  copyright:
    - license: "GPL-2.0-or-later"

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - docbook-xml
      - git
      - libevent
      - libevent-dev
      - libmemcached-dev
      - libtool
      - libxml2-utils
      - libxslt
      - m4
      - openssl-dev
      - pcre-dev
      - pkgconf
      - pkgconf-dev
      - py3-pip
      - python3
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/RedisLabs/memtier_benchmark
      tag: ${{package.version}}
      expected-commit: 17704780925f45c0ba24de169c9d7df6a7449d3c

  - runs: |
      autoreconf -fiv

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

update:
  enabled: true
  github:
    identifier: RedisLabs/memtier_benchmark

test:
  pipeline:
    - runs: |
        memtier_benchmark --version | grep ${{package.version}}
        memtier_benchmark help
