package:
  name: mountpoint-s3-csi-driver
  version: 1.9.0
  epoch: 0
  description: Built on Mountpoint for Amazon S3, the Mountpoint CSI driver presents an Amazon S3 bucket as a storage volume accessible by containers in your Kubernetes cluster
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/awslabs/mountpoint-s3-csi-driver
      tag: v${{package.version}}
      expected-commit: 2c96c14bffa755e61b4d5dfbb4913278589526e5

  - uses: go/build
    with:
      packages: ./cmd/aws-s3-csi-driver
      ldflags: |
        -X github.com/awslabs/aws-s3-csi-driver/pkg/driver/version.driverVersion=${{package.version}}
        -X github.com/awslabs/aws-s3-csi-driver/pkg/driver/version.gitCommit=$(git rev-parse HEAD)
        -X github.com/awslabs/aws-s3-csi-driver/pkg/driver/version.buildDate=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      output: aws-s3-csi-driver

  - uses: go/build
    with:
      packages: ./cmd/install-mp
      ldflags: |
        -X github.com/awslabs/aws-s3-csi-driver/pkg/driver/version.driverVersion=${{package.version}}
        -X github.com/awslabs/aws-s3-csi-driver/pkg/driver/version.gitCommit=$(git rev-parse HEAD)
        -X github.com/awslabs/aws-s3-csi-driver/pkg/driver/version.buildDate=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      output: install-mp

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/bin/
          ln -sf /usr/bin/aws-s3-csi-driver ${{targets.contextdir}}/bin/aws-s3-csi-driver
          ln -sf /usr/bin/install-mp ${{targets.contextdir}}/bin/install-mp

update:
  enabled: true
  github:
    identifier: awslabs/mountpoint-s3-csi-driver
    strip-prefix: v

test:
  pipeline:
    - runs: |
        aws-s3-csi-driver --version
        aws-s3-csi-driver --help
