package:
  name: multipath-tools
  version: 0.10.0
  epoch: 1
  description: Device Mapper Multipathing Driver
  copyright:
    - license: LGPL-2.0-only

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - device-mapper
      - eudev
      - eudev-dev
      - json-c-dev
      - libaio-dev
      - lvm2-dev
      - ncurses-dev
      - perl
      - readline-dev
      - userspace-rcu-dev
      - util-linux-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/opensvc/multipath-tools
      expected-commit: ee3a70175a8a9045e5c309d5392300922e2a0625
      tag: ${{package.version}}

  - uses: autoconf/make
    with:
      opts: LIB=/lib exec_prefix=/usr

  - uses: autoconf/make-install
    with:
      opts: LIB=/lib exec_prefix=/usr

  - uses: strip

subpackages:
  - name: multipath-tools-doc
    pipeline:
      - uses: split/manpages
    description: multipath-tools manpages

update:
  enabled: true
  github:
    identifier: opensvc/multipath-tools
    use-tag: true

test:
  pipeline:
    - runs: |
        # very basic tests to ensure it built and installed
        # note that functional tests would take much more complexity
        multipath -h
        mpathpersist -h
        [ -x /usr/sbin/kpartx ]
        mpathpersist --help
        multipathd version
        multipathd help
