package:
  name: nfs-ganesha
  version: "6.1"
  epoch: 0
  description: NFS-Ganesha is an NFSv3,v4,v4.1 fileserver that runs in user mode on most UNIX/Linux systems
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - acl-dev
      - autoconf
      - automake
      - bind-tools
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - flex
      - gcc-12-default
      - krb5-dev
      - libnsl
      - libnsl-dev
      - libtirpc
      - libtirpc-dev
      - openssf-compiler-options
      - userspace-rcu-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: e13bc5dae062f4c34780137d9845db2fde7dbccb
      repository: https://github.com/nfs-ganesha/nfs-ganesha
      tag: V${{package.version}}
      recurse-submodules: true

  # This patch adds a missing assert header which is required in newer gcc
  - working-directory: src/libntirpc
    pipeline:
      - uses: patch
        with:
          patches: ../../assert.patch

  - working-directory: src
    pipeline:
      - uses: cmake/configure
      - uses: cmake/build
      - uses: cmake/install
      - uses: strip

subpackages:
  - name: nfs-ganesha-dev
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: nfs-ganesha/nfs-ganesha
    strip-prefix: V
    tag-filter: V

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        ganesha.nfsd version
        ganesha.nfsd help
