package:
  name: npth
  version: "1.7"
  epoch: 2
  description: The New GNU Portable Threads library
  copyright:
    - license: LGPL-3.0-or-later OR GPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: git://git.gnupg.org/npth.git
      tag: npth-${{package.version}}
      expected-commit: 150dc11942c90ff8190c2d48344eb4c1c48c7cd8

  - runs: ./autogen.sh

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: npth-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - npth
    description: npth dev
    test:
      pipeline:
        - uses: test/pkgconf

update:
  enabled: true
  release-monitor:
    identifier: 2505
