package:
  name: nrjmx
  version: 2.6.0
  epoch: 0
  description: Command line tool to connect to a JMX server and retrieve the MBeans it exposes
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - openjdk-17-jre

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - curl
      - maven
      - openjdk-17
      - openjdk-17-default-jvm
      - wolfi-base
      - wolfi-baselayout
  environment:
    LANG: en_US.UTF-8
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nrjmx
      tag: v${{package.version}}
      expected-commit: 9fddfa34e08e719410d858a828218c7e315bc069

  - uses: maven/configure-mirror

  - runs: |
      mvn clean package -P \!deb,\!rpm,\!tarball,\!test -DskipTests

      mkdir -p ${{targets.destdir}}/usr/share/java/nrjmx/bin

      install -m755 ./bin/* ${{targets.destdir}}/usr/share/java/nrjmx/bin/

      mkdir -p ${{targets.destdir}}/usr/bin
      for i in nrjmx nrjmx.jar; do
        ln -sf /usr/share/java/nrjmx/bin/$i ${{targets.destdir}}/usr/bin/$i
      done

update:
  enabled: true
  github:
    identifier: newrelic/nrjmx
    strip-prefix: v
