package:
  name: openmpi
  version: 5.0.5
  epoch: 0
  description: Message passing library for high-performance computing
  copyright:
    - license: BSD-3-Clause-Open-MPI AND mpich2
  dependencies:
    runtime:
      - hwloc
      - openpmix
      - prrte

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils
      - flex
      - flex-dev
      - gfortran
      - hwloc-dev
      - libevent-dev
      - libgomp
      - libtool
      - libxml2
      - libxml2-dev
      - openpmix-dev
      - perl
      - posix-libc-utils
      - prrte-dev
      - py3-recommonmark
      - py3-sphinx-7
      - py3-sphinx-rtd-theme
      - python-3.12-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/open-mpi/ompi
      tag: v${{package.version}}
      expected-commit: ca64c52a8227b4b3f3ee255a644ba4686ee9e600
      recurse-submodules: true

  - runs: |
      perl autogen.pl
      chmod +x configure
      # workaround for https://github.com/open-mpi/ompi/issues/12257
      # see https://gitlab.archlinux.org/archlinux/packaging/packages/openmpi/-/blob/main/PKGBUILD#L51-54
      sed -i 's|WRAPPER__FCFLAGS|WRAPPER_FCFLAGS|g' configure
      sed -i 's|WRAPPER_EXTRA_FCFLAGS|WRAPPER_FCFLAGS|g' configure
      sed -i 's|"-I/usr/include",||' opal/tools/wrappers/opal_wrapper.c

  - uses: autoconf/configure
    with:
      opts: |
        --with-prefix=/usr \
        --with-libevent=external \
        --with-hwloc=external \
        --with-pmix=external \
        --with-prrte=external

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  # note no doc subpackage the files in /usr/share/openmpi are needed by the wrappers
  - name: openmpi-dev
    description: openmpi dev
    dependencies:
      runtime:
        - ${{package.name}}
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/pkgconf

  - name: openmpi-doc
    description: openmpi manpages
    pipeline:
      - uses: split/manpages

test:
  environment:
    contents:
      packages:
        - build-base
        - gfortran
        - openjdk-17-default-jdk
        - openmpi
        - openmpi-dev
        - openpmix-dev
  pipeline:
    - uses: git-checkout
      with:
        repository: https://github.com/open-mpi/ompi
        tag: v${{package.version}}
        expected-commit: ca64c52a8227b4b3f3ee255a644ba4686ee9e600
        recurse-submodules: true
      runs: |
        mpiCC --version
        mpiCC --help
        mpic++ --version
        mpic++ --help
        mpicc --version
        mpicc --help
        mpicxx --version
        mpicxx --help
        mpiexec --version
        mpiexec --help
        mpirun --version
        mpirun --help
        ompi_info --version
        ompi_info --help
        oshrun --version
        oshrun --help
    - runs: |
        cd examples
        mpifort --showme
        make

update:
  enabled: true
  github:
    identifier: open-mpi/ompi
    strip-prefix: v
    use-tag: true
