package:
  name: opentelemetry-cpp
  version: 1.17.0
  epoch: 1
  description: The OpenTelemetry C++ Client
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - abseil-cpp-dev
      - benchmark-dev
      - busybox
      - c-ares-dev
      - cmake
      - gcc
      - glibc-dev
      - grpc-dev
      - gtest-dev
      - icu-dev
      - make
      - openssl-dev
      - pkgconf
      - protobuf-dev
      - re2-dev
      - systemd-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/open-telemetry/opentelemetry-cpp
      tag: v${{package.version}}
      expected-commit: fa0a5200ddbe9ae6f487a228e658aedc102dab56

  - uses: cmake/configure
    with:
      opts: -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBUILD_SHARED_LIBS=ON -DWITH_OTLP_GRPC=ON -DWITH_ABSEIL=ON

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: opentelemetry-cpp-dev
    description: The OpenTelemetry C++ Client development files
    dependencies:
      runtime:
        - opentelemetry-cpp
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: open-telemetry/opentelemetry-cpp
    strip-prefix: v
