package:
  name: opentelemetry-collector-contrib
  version: 0.111.0
  epoch: 0
  description: Contrib repository for the OpenTelemetry Collector
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/open-telemetry/opentelemetry-collector-contrib
      tag: v${{package.version}}
      expected-commit: 47cd38d9815a854873962c17aa8df4bbe71268d8

  # https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35631
  - runs: |
      make genotelcontribcol

  - uses: go/build
    with:
      modroot: ./cmd/otelcontribcol
      packages: .
      output: otelcol-contrib
      go-package: go

subpackages:
  - name: opentelemetry-collector-contrib-compat
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart expects the binaries to be in / instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/otelcol-contrib ${{targets.subpkgdir}}/otelcol-contrib

update:
  enabled: true
  github:
    identifier: open-telemetry/opentelemetry-collector-contrib
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        otelcol-contrib --version
        otelcol-contrib --help
