package:
  name: perl-capture-tiny
  version: "0.48"
  epoch: 2
  description: Capture STDOUT and STDERR from Perl, XS or external programs
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev

pipeline:
  - uses: fetch
    with:
      expected-sha512: 96d140b33a5ee147804925353ec5b49b806fa9c98b4ac23ec9c9494828f52ac72fd6f69c08e14ada18e5187dc4cece3d72901ce07b12eef20595322161a98437
      uri: https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Capture-Tiny-${{package.version}}.tar.gz

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

subpackages:
  - name: perl-capture-tiny-doc
    pipeline:
      - uses: split/manpages
    description: perl-capture-tiny manpages

update:
  enabled: true
  release-monitor:
    identifier: 2677
