package:
  name: pip-zipapp
  version: "24.2"
  epoch: 1
  description: "Pip as a python zipapp"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox

# See https://pip.pypa.io/en/stable/installation/#standalone-zip-application
# Wheels for installer, setuptools, tomli, wheel, flit-core
#
# Hashes available from pypi (built distribution is the wheel)
# https://pypi.org/project/installer/0.7.0/#files
# https://pypi.org/project/setuptools/70.0.0/#files
# https://pypi.org/project/tomli/2.0.1/#files
# https://pypi.org/project/wheel/#files
# https://pypi.org/project/flit-core/#files
pipeline:
  - uses: fetch
    with:
      uri: https://bootstrap.pypa.io/pip/zipapp/pip-${{package.version}}.pyz
      expected-sha256: b376f160ac1cf3ffe3434e9b770dd1c9fb019edf028ba7ba3f675a159f30d06c
      extract: false
  - uses: fetch
    with:
      uri: "https://files.pythonhosted.org/packages/py3/i/installer/installer-0.7.0-py3-none-any.whl"
      expected-sha256: "05d1933f0a5ba7d8d6296bb6d5018e7c94fa473ceb10cf198a92ccea19c27b53"
      extract: false
  - uses: fetch
    with:
      uri: "https://files.pythonhosted.org/packages/py3/s/setuptools/setuptools-72.1.0-py3-none-any.whl"
      expected-sha256: "5a03e1860cf56bb6ef48ce186b0e557fdba433237481a9a625176c2831be15d1"
      extract: false
  - uses: fetch
    with:
      uri: "https://files.pythonhosted.org/packages/py3/t/tomli/tomli-2.0.1-py3-none-any.whl"
      expected-sha256: "939de3e7a6161af0c887ef91b7d41a53e7c5a1ca976325f429cb46ea9bc30ecc"
      extract: false
  - uses: fetch
    with:
      uri: "https://files.pythonhosted.org/packages/py3/w/wheel/wheel-0.44.0-py3-none-any.whl"
      expected-sha256: "2376a90c98cc337d18623527a97c31797bd02bad0033d41547043a1cbfbe448f"
      extract: false
  - uses: fetch
    with:
      uri: "https://files.pythonhosted.org/packages/py3/f/flit_core/flit_core-3.9.0-py3-none-any.whl"
      expected-sha256: "7aada352fb0c7f5538c4fafeddf314d3a6a92ee8e2b1de70482329e42de70301"
      extract: false
  - runs: |
      destd=${{targets.destdir}}
      sdir=usr/share/${{package.name}}
      fname=${{package.name}}.pyz
      mkdir -p "$destd/$sdir"
      cp "pip-${{package.version}}.pyz" "$destd/$sdir/$fname"
      chmod 0644 "$destd/$sdir/$fname"

      mkdir -p "$destd/$sdir/wheels"
      cp *.whl "$destd/$sdir/wheels/"

update:
  enabled: true
  ignore-regex-patterns:
    - 'b'
  github:
    identifier: pypa/pip
    use-tag: true
