package:
  name: podman
  version: 5.2.5
  epoch: 0
  description: "A tool for managing OCI containers and pods"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - btrfs-progs
      - btrfs-progs-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils
      - crun
      - device-mapper-libs
      - go
      - go-md2man
      - gpgme
      - gpgme-dev
      - grep
      - iptables
      - iptables-dev
      - libassuan-dev
      - libgpg-error-dev
      - libprotobuf
      - libseccomp-dev
      - libsystemd
      - man-db
      - pkgconf
      - pkgconf-dev
      - protobuf-c-dev
      - python3
      - shadow-subids
      - systemd-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/containers/podman
      tag: v${{package.version}}
      expected-commit: 10c5aa720d59480bc7edad347c1f5d5b75d4424f

  - uses: go/bump
    with:
      deps: github.com/opencontainers/runc@v1.1.14

  - runs: |
      make
      # Would be great to run these tests eventually, but requires podman and a privileged container to do networking stuff
      #make test
      make docs
      PREFIX=/usr DESTDIR="${{targets.destdir}}" make install

  - uses: strip

subpackages:
  - name: "podman-doc"
    description: "podman documentation"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  github:
    identifier: containers/podman
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        podman --help
        podman --version
        podman-remote --version
        podman-remote --help
