package:
  name: prometheus-mongodb-exporter
  version: 0.41.2
  epoch: 0
  description: A Prometheus exporter for MongoDB including sharding, replication and storage engines
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/percona/mongodb_exporter
      expected-commit: d368da1f1fca82c635af49c2d2dd612999cb3883
      tag: v${{package.version}}

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv mongodb_exporter ${{targets.destdir}}/usr/bin/

  - uses: strip

subpackages:
  - name: prometheus-mongodb-exporter-bitnami-compat
    description: "compat package with bitnami/mongodb helm chart"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/bin
          ln -s /usr/bin/mongodb_exporter "${{targets.subpkgdir}}"/bin/mongodb_exporter

update:
  enabled: true
  github:
    identifier: percona/mongodb_exporter
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        mongodb_exporter --version
        mongodb_exporter --help
