package:
  name: py3-sphinxcontrib-jsmath
  version: 1.0.1
  epoch: 4
  description: A sphinx extension which renders display math in HTML via JavaScript
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sphinx-doc/sphinxcontrib-jsmath
      expected-commit: e4c69dd2180c7f18330d5c3fb9300ea0e8461911
      tag: ${{package.version}}

  - name: Python Build
    runs: |
      python3 -m build

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/sphinxcontrib_jsmath*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: sphinx-doc/sphinxcontrib-jsmath
    use-tag: true
