package:
  name: py3-sphinxcontrib-serializinghtml
  version: 2.0.0
  epoch: 1
  description: sphinxcontrib-serializinghtml is a sphinx extension which outputs "serialized" HTML files (json and pickle)
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sphinx-doc/sphinxcontrib-serializinghtml
      expected-commit: f0f3b15b2e6bb47570d605ebd5687643d7a85b9d
      tag: ${{package.version}}

  - name: Python Build
    runs: |
      python3 -m build

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/sphinxcontrib_serializinghtml*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: sphinx-doc/sphinxcontrib-serializinghtml
