package:
  name: py3-sphinxcontrib-qthelp
  version: 2.0.0
  epoch: 1
  description: sphinxcontrib-qthelp is a sphinx extension which outputs QtHelp documents
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sphinx-doc/sphinxcontrib-qthelp
      expected-commit: 783caf58e9ba9cf0450746b7f65d4bc8229ccd8f
      tag: ${{package.version}}

  - name: Python Build
    runs: |
      python3 -m build

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/sphinxcontrib_qthelp*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: sphinx-doc/sphinxcontrib-qthelp
