package:
  name: py3-sphinxcontrib-htmlhelp
  version: 2.1.0
  epoch: 1
  description: sphinxcontrib-htmlhelp is a sphinx extension which renders HTML help files
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sphinx-doc/sphinxcontrib-htmlhelp
      expected-commit: f7f5d4ecf27fad97e2454fbeda94c6a105c994ff
      tag: ${{package.version}}

  - name: Python Build
    runs: |
      python3 -m build

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/sphinxcontrib_htmlhelp*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: sphinx-doc/sphinxcontrib-htmlhelp
