package:
  name: py3-sphinxcontrib-devhelp
  version: 2.0.0
  epoch: 1
  description: sphinxcontrib-devhelp is a sphinx extension which outputs Devhelp documents
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sphinx-doc/sphinxcontrib-devhelp
      expected-commit: 0177fb44f165305f27b34e69e6e7e5ed6f24d752
      tag: ${{package.version}}

  - name: Python Build
    runs: |
      python3 -m build

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/sphinxcontrib_devhelp*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: sphinx-doc/sphinxcontrib-devhelp
