package:
  name: py3-tomli
  version: 2.0.2
  epoch: 0
  description: TOML parser
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: tomli

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"
      3.13: "300"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py3-supported-installer
      - py3-supported-python

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/py3/t/tomli/tomli-${{package.version}}-py3-none-any.whl
      expected-sha256: 2ebe24485c53d303f690b0ec092806a085f07af5a5aa1464f3931eec36caaa38
      extract: false

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - ${{package.name}}
    pipeline:
      - runs: |
          python${{range.key}} -m installer -d "${{targets.subpkgdir}}" \
            tomli-${{package.version}}-py3-none-any.whl
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}

update:
  enabled: true
  release-monitor:
    identifier: 207408
