package:
  name: py3-pyjwt
  version: 2.9.0
  epoch: 1
  description: JSON Web Token implementation in Python
  copyright:
    - license: MIT
  dependencies:
    provider-priority: "0"

data:
  - name: py-versions
    items:
      "3.10": "310"
      "3.11": "311"
      "3.12": "312"
      "3.13": "300"

vars:
  module_name: jwt
  pypi-package: pyjwt

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-supported-pip
      - py3-supported-setuptools
      - py3-supported-setuptools-scm
      - py3-supported-typing-extensions
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jpadilla/pyjwt
      tag: ${{package.version}}
      expected-commit: 868cf4ab2ca5a0a39da40e5a14dd740b203662b2

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    pipeline:
      - name: Python Build
        uses: py/pip-build-install
        with:
          python: python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-typing-extensions
      provides:
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    test:
      pipeline:
        - name: Import Test
          uses: python/import
          with:
            import: ${{vars.module_name}}

update:
  enabled: true
  github:
    identifier: jpadilla/pyjwt

test:
  pipeline:
    - name: Import Test
      uses: python/import
      with:
        import: ${{vars.module_name}}
