package:
  name: py3-ruamel-yaml-clib
  version: 0.2.12
  epoch: 0
  description: "C version of reader, parser and emitter for ruamel.yaml derived from libyaml."
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - gcc~13
      - openssf-compiler-options
      - py3-gpep517
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/r/ruamel.yaml.clib/ruamel.yaml.clib-${{package.version}}.tar.gz
      expected-sha256: 6c8fbb13ec503f99a91901ab46e0b07ae7941cd527393187039aec586fdfd36f

  - uses: py/pip-build-install

  - runs: |
      install -Dm644 LICENSE \
        "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 131030
