package:
  name: py3-scikit-optimize
  version: 0.9.0
  epoch: 2
  description: Sequential model-based optimization toolbox.
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - numpy
      - py3-joblib
      - py3-matplotlib
      - py3-pillow
      - py3-pyyaml
      - py3-scikit-learn
      - py3-scipy
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cython
      - numpy
      - py3-scipy
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/scikit-optimize/scikit-optimize
      expected-commit: a2369ddbc332d16d8ff173b12404b03fea472492
      tag: v${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: scikit-optimize/scikit-optimize
    strip-prefix: v
