package:
  name: py3-sphinxcontrib-applehelp
  version: 2.0.0
  epoch: 1
  description: sphinxcontrib-applehelp is a Sphinx extension which outputs Apple help books
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sphinx-doc/sphinxcontrib-applehelp
      expected-commit: f4f9d900b238d03da601bf7c75cff5bcbcee6d7c
      tag: ${{package.version}}

  - name: Python Build
    runs: |
      python3 -m build

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/sphinxcontrib_applehelp*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: sphinx-doc/sphinxcontrib-applehelp
