package:
  name: py3-pyproject-metadata
  version: 0.8.1
  epoch: 0
  description: PEP 621 metadata parsing
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: pyproject-metadata
  module-name: pyproject_metadata

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"
      3.13: "300"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-supported-flit-core
      - py3-supported-pip
      - py3-supported-python
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypa/pyproject-metadata
      tag: ${{package.version}}
      expected-commit: b7b59c4982565bca76108522f925997f37289276

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py3-packaging
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}

test:
  pipeline:
    - runs: python3.12 -c "import ${{vars.module-name}}"

update:
  enabled: true
  ignore-regex-patterns:
    - a
    - b
    - rc
    - post
  github:
    identifier: pypa/pyproject-metadata
    use-tag: true
