package:
  name: py3-pykube-ng
  version: 23.6.0
  epoch: 1
  description: Pykube (pykube-ng) is a lightweight Python 3.6+ client library for Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-google-auth
      - py3-pyyaml
      - py3-requests
      - py3-requests-oauthlib
      - py3-urllib3
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pyyaml
      - py3-requests
      - python-3
      - python-3-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://codeberg.org/hjacobs/pykube-ng.git
      tag: ${{package.version}}
      expected-commit: c1ac2c97587249e418d04d91f1297d4ffe3631c3

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: false
  manual: true
  exclude-reason: we need to manually update because it does not use github
