package:
  name: py3-rfc3339
  version: 1.1
  epoch: 2
  description: Generate and parse RFC 3339 timestamps
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py3-tz
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kurtraschke/pyRFC3339
      expected-commit: e30cc1555adce0ecc7bd65509a2249d47e5a41b4
      tag: v${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: kurtraschke/pyRFC3339
    strip-prefix: v
