package:
  name: py3-sphinx
  version: 8.1.1
  epoch: 0
  description: "Python Documentation Generator"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py3-alabaster
      - py3-babel
      - py3-docutils
      - py3-imagesize
      - py3-jinja2
      - py3-packaging
      - py3-pygments
      - py3-requests
      - py3-snowballstemmer
      - py3-sphinxcontrib-applehelp
      - py3-sphinxcontrib-devhelp
      - py3-sphinxcontrib-htmlhelp
      - py3-sphinxcontrib-jsmath
      - py3-sphinxcontrib-qthelp
      - py3-sphinxcontrib-serializinghtml

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-flit-core
      - py3-gpep517
      - py3-installer
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sphinx-doc/sphinx
      tag: v${{package.version}}
      expected-commit: 61d88859d79cff69f16da20294dceedb5e653f95

  - runs: |
      mkdir -p dist
      backend="$(python3 -m gpep517 get-backend)"
      python3 -m gpep517 build-wheel --wheel-dir dist --backend "$backend" --output-fd 1

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/sphinx-*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: sphinx-doc/sphinx
    strip-prefix: v

test:
  pipeline:
    - uses: python/import
      with:
        import: sphinx
      runs: |
        sphinx-build --version
        sphinx-build --help
        sphinx-apidoc --version
        sphinx-apidoc --help
        sphinx-autogen --version
        sphinx-autogen --help
        sphinx-quickstart --version
        sphinx-quickstart --help
