package:
  name: py3-tensorflow-serving-api
  version: 2.17.0
  epoch: 0
  description: A flexible, high-performance serving system for machine learning models
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-grpcio
      - py3-protobuf
      - py3-tensorflow-core
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-installer
      - py3-pip
      - py3-setuptools
      - python-3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6311b72ea7efdc8c306de3c3bc808388468b7a3d
      repository: https://github.com/tensorflow/serving
      tag: ${{package.version}}

  - name: Download tensorflow-serving-api from PyPI
    runs: |
      # FIXME: This is a hack to get around the fact that tensorflow-serving-api is not
      # get built as a wheel on Wolfi due to latest Tensorflow requirement.
      pip install tensorflow-serving-api --no-deps --ignore-requires-python --prefix=/usr --root=${{targets.destdir}}

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: tensorflow/serving

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - uses: python/import
      with:
        import: tensorflow_serving
