package:
  name: rancher-fleet
  version: 0.10.3
  epoch: 0
  description: Deploy workloads from Git to large fleets of Kubernetes clusters
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d6613fdfea5df5ba7fbdff69fb3029886d29e5f2
      repository: https://github.com/rancher/fleet
      tag: v${{package.version}}

subpackages:
  - name: ${{package.name}}-agent
    pipeline:
      - uses: go/build
        with:
          ldflags: -X github.com/rancher/fleet/pkg/version.GitCommit=$(git rev-parse HEAD) -X github.com/rancher/fleet/pkg/version.Version=${{package.version}}
          modroot: ./cmd/fleetagent
          output: fleetagent
          packages: .
    test:
      pipeline:
        - runs: |
            fleetagent --version

update:
  enabled: true
  github:
    identifier: rancher/fleet
    strip-prefix: v
