package:
  name: rancher-webhook-0.5
  version: 0.5.3
  epoch: 0
  description: Rancher webhook for Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - rancher-webhook=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 602351ab4887e07473908437610e7d7d01c489f2
      repository: https://github.com/rancher/webhook
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: k8s.io/kubernetes@v1.30.3 k8s.io/apiserver@v0.30.3
      modroot: .

  - uses: go/build
    with:
      modroot: .
      output: webhook
      packages: .

update:
  enabled: true
  git:
    strip-prefix: v
    tag-filter-prefix: v0.5.
