package:
  name: rpcbind
  version: 1.2.7
  epoch: 0
  description: portmap replacement which supports RPC over various protocols
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtirpc-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: f6edf8cdf562aedd5d53b8bf93962d61623292bfc4d47eedd3f427d84d06f37e
      uri: https://downloads.sourceforge.net/project/rpcbind/rpcbind/${{package.version}}/rpcbind-${{package.version}}.tar.bz2

  - uses: autoconf/configure
    with:
      opts: |
        --enable-warmstarts \
        --with-statedir=/var/lib/rpcbind \
        --with-rpcuser=rpc \
        --enable-debug \
        --with-systemdsystemunitdir='no'

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: rpcbind-doc
    pipeline:
      - uses: split/manpages
    description: rpcbind manpages

update:
  enabled: true
  release-monitor:
    identifier: 4212
