package:
  name: rrdtool
  version: 1.9.0
  epoch: 0
  description: Data logging and graphing application
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - cairo
      - cairo-dev
      - expat-dev
      - font-sony-misc
      - freetype-dev
      - fribidi-dev
      - glib-dev
      - glibc-dev
      - groff
      - harfbuzz-dev
      - libart-lgpl-dev
      - libpng-dev
      - libtool
      - libxft-dev
      - libxml2-dev
      - lua5.4
      - lua5.4-dev
      - pango
      - pango-dev
      - pcre2-dev
      - perl-dev
      - perl-xml-parser
      - pkgconf-dev
      - posix-libc-utils
      - py3.12-setuptools
      - python3-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/oetiker/rrdtool-1.x
      expected-commit: 522b228d74da7054594b6ed9c289058acd6cd3e7
      tag: v${{package.version}}

  - runs: |
      export CPPFLAGS="-I/usr/include/pango-1.0/pango"

  - uses: autoconf/configure
    with:
      opts: |
        --prefix=/usr \
        --disable-nls \
        --disable-tcl \
        --disable-ruby \
        --enable-rrdcgi \
        --enable-perl-site-install \
        --enable-lua-site-install \
        --with-perl-options="INSTALLDIRS=vendor"

  - runs: |
      export INSTALLDIRS=vendor
      make DESTDIR="${{targets.destdir}}" install
      find "${{targets.destdir}}" -name '.packlist' -delete
      find "${{targets.destdir}}" -name 'perllocal.pod' -delete

  - uses: strip

subpackages:
  - name: rrdtool-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - rrdtool
        - font-sony-misc
    description: rrdtool dev
    test:
      pipeline:
        - uses: test/pkgconf

  - name: rrdtool-doc
    pipeline:
      - uses: split/manpages
    description: rrdtool manpages

  - name: perl-rrd
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib \
          	"${{targets.destdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/lib/perl* "${{targets.subpkgdir}}"/usr/lib/
          mv "${{targets.destdir}}"/usr/share/perl* "${{targets.subpkgdir}}"/usr/share/
    description: Perl interface for rrdtool

  - name: lua-rrd
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/
          mv /usr/lib/lua* "${{targets.subpkgdir}}"/usr/lib/
    description: Lua interface for rrdtool

  - name: rrdtool-cached
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/sbin \
          	"${{targets.subpkgdir}}"/var/lib/rrdcached/db \
          	"${{targets.subpkgdir}}"/var/lib/rrdcached/journal
          mv "${{targets.destdir}}"/usr/bin/rrdcached "${{targets.subpkgdir}}"/usr/sbin
    description: RRDtool data caching daemon
    dependencies:
      runtime:
        - rrdtool
    test:
      pipeline:
        - runs: |
            rrdcached --version
            rrdcached help

  - name: rrdtool-cached-openrc
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/etc/init.d
          install -Dm755 ./rrdcached.initd "${{targets.subpkgdir}}"/etc/init.d/rrdcached
    description: RRDtool data caching daemon (OpenRC init scripts)

  - name: rrdtool-cgi
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/rrdcgi "${{targets.subpkgdir}}"/usr/bin
    description: create web pages containing RRD graphs based on templates

  - name: rrdtool-utils
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/rrdinfo \
          	"${{targets.destdir}}"/usr/bin/rrdcreate \
          	"${{targets.destdir}}"/usr/bin/rrdupdate \
          	"${{targets.subpkgdir}}"/usr/bin
    description: RRDtool standalone create,update,info utilities

update:
  enabled: true
  github:
    identifier: oetiker/rrdtool-1.x
    strip-prefix: v

test:
  pipeline:
    - name: Verify rrdtool installation
      runs: |
        rrdtool --version | grep ${{package.version}} || exit 1
        rrdtool --help
