package:
  name: ruby3.2-fluent-config-regexp-type
  version: 1.0.0
  epoch: 3
  description: Backport regex type for fluentd
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby3.2-fluentd

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: fluent-config-regexp-type

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0f68084a0110405bb45743449dfbef6fbde203e6
      repository: https://github.com/okkez/fluent-config-regexp-type
      tag: v${{package.version}}

  - uses: ruby/unlock-spec

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: okkez/fluent-config-regexp-type
    strip-prefix: v
    use-tag: true
