package:
  name: ruby3.2-attr_required
  version: 1.0.2
  epoch: 1
  description: attr_required and attr_optional
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/nov/attr_required
      tag: v${{package.version}}
      expected-commit: a48a5f1f83bffff24a58b96c30b8a5cf15c56d8f

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: attr_required

update:
  enabled: true
  github:
    identifier: nov/attr_required
    strip-prefix: v
    use-tag: true
