package:
  name: ruby3.2-validate_email
  version: 0.1.6
  epoch: 5
  description: Library for validating email addresses in Rails 3 models.
  dependencies:
    runtime:
      - ruby3.2-activemodel
      - ruby3.2-mail
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: http://github.com/perfectline/validates_email
      tag: v${{package.version}}
      expected-commit: 25a5efcd7b4daa6445d3be9e8ba103b174ba9e4b

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: validate_email

update:
  enabled: true
  github:
    identifier: perfectline/validates_email
    strip-prefix: v
    use-tag: true
