#nolint:valid-pipeline-git-checkout-tag
package:
  name: ruby3.2-aws-sigv4
  version: 1.9.0
  epoch: 1
  description: Amazon Web Services Signature Version 4 signing library. Generates sigv4 signature for HTTP requests.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby3.2-aws-eventstream

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 761b5a43e8c97577e5fbb9f1eceb47cbde56be65
      repository: https://github.com/aws/aws-sdk-ruby
      branch: version-3
      depth: -1

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
      dir: gems/${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
      dir: gems/${{vars.gem}}

  - uses: ruby/clean

vars:
  gem: aws-sigv4

update:
  enabled: false
  manual: true # the library we fetch uses a different version then the package version
  release-monitor:
    identifier: 174496
