package:
  name: ruby3.2-async-pool
  version: 0.10.1
  epoch: 0
  description: A singleplex and multiplex resource pool for implementing robust clients.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2
      - ruby3.2-async
      - ruby3.2-metrics
      - ruby3.2-traces

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: async-pool

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 2b213d0cbdca13888233542268973a695196e95a
      repository: https://github.com/socketry/async-pool
      tag: v${{package.version}}

  - runs: sed -i '/signing_key/d' ${{vars.gem}}.gemspec

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/async-pool
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        ruby -e "require 'async/pool'"
