package:
  name: snmalloc
  version: "0.6.2"
  epoch: 0
  description: "snmalloc is a high-performance, message passing based allocator."
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - glibc

environment:
  contents:
    packages:
      - bash
      - binutils
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang-18
      - clang-18-dev
      - clang-18-extras
      - cmake
      - coreutils
      - llvm-lld-18
      - samurai
      - scanelf
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/microsoft/snmalloc/archive/refs/tags/${{package.version}}.tar.gz
      expected-sha256: e0486ccf03eac5dd8acbb66ea8ad33bec289572a51614acdf7117397e4f1af8c

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_C_COMPILER=clang \
        -DCMAKE_CXX_COMPILER=clang++ \
        -DSNMALLOC_BUILD_TESTING=OFF \
        -DSNMALLOC_LINK_ICF=ON \
        -DSNMALLOC_IPO=ON \
        -DSNMALLOC_STATIC_LIBRARY_PREFIX=

  - uses: cmake/build

  # TODO: have a cmake/test pipeline
  #          for working with the cmake/build pipeline
  # - runs: |
  #     ctest --output-on-failure -j "$(nproc)" -C Release --timeout 400

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: snmalloc-static
    pipeline:
      - uses: split/static
    description: snmalloc static library

  - name: snmalloc-dev
    pipeline:
      - uses: split/dev
    description: header files of snmallac

test:
  environment:
    contents:
      packages:
        - wolfi-base
        - stress-ng
  pipeline:
    - runs: |
        LD_PRELOAD=/usr/lib/libsnmallocshim.so                    stress-ng --vdso 1 -t 5 --metrics
        LD_PRELOAD=/usr/lib/libsnmallocshim-checks.so             stress-ng --vdso 1 -t 5 --metrics
        LD_PRELOAD=/usr/lib/libsnmallocshim-checks-memcpy-only.so stress-ng --vdso 1 -t 5 --metrics

update:
  enabled: true
  github:
    identifier: microsoft/snmalloc
    use-tag: true
  ignore-regex-patterns:
    - "v.*"
