package:
  name: superset
  version: 4.0.2
  epoch: 3
  description: Data Visualization and Data Exploration Platform
  copyright:
    - license: Apache-2.0
  options:
    #  There is a dependency on libarrow-substrait.so although it
    #  is provided in the virtual environment. Enabling no-depends
    #  works around this
    no-depends: true
  dependencies:
    runtime:
      - openssl
      - python-3.11

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - mariadb-connector-c-dev
      - mariadb-dev
      - nodejs
      - npm
      - nvm
      - openldap-dev
      - py3-sqlparse
      - py3.11-pip
      - python-3.11-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/superset.git
      tag: ${{package.version}}
      expected-commit: f11fa091e261a35f4d39d8567a859fad07547d84

  - uses: patch
    with:
      # to relax gunicorn and sqlparse version requirements
      patches: version-requirements.patch

  - runs: |
      # Back-end build

      python -m venv venv --system-site-packages
      source venv/bin/activate

      # To install mysqlclient wheel
      export MYSQLCLIENT_CFLAGS=`mysql_config --cflags`
      export MYSQLCLIENT_LDFLAGS=`mysql_config --libs`

      pip install -r requirements/base.txt

      # To fix vulnerabilities
      pip install --upgrade dnspython==2.6.1 gunicorn==22.0.0 idna==3.7 setuptools==70.0.0 sqlparse==0.5.0 Jinja2==3.1.4 Werkzeug==3.0.3 requests==2.32.0 urllib3==1.26.19 certifi==2024.07.04 zipp==3.19.2
      # Dependencies required during runtime
      pip install pillow pyarrow
      # For running translations
      pip install flask flask-appbuilder

      # Build Apache Superset
      pip install .

      # translations for the web application, Is a non-blocking call, so errors may be ignored
      flask fab babel-compile --target superset/translations

  - runs: |
      # Front-end build
      cd superset-frontend
      npm install
      npm run build

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/superset
      mv venv ${{targets.destdir}}/usr/share/superset
      rm -rf ${{targets.destdir}}/usr/share/superset/venv/bin/__pycache*
      sed -i "s|/home/build|/usr/share/superset|g" ${{targets.destdir}}/usr/share/superset/venv/bin/*

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin/
      cp  ./docker/run-server.sh ${{targets.destdir}}/usr/bin/
      chmod 755 ${{targets.destdir}}/usr/bin/run-server.sh

      mkdir -p ${{targets.destdir}}/app/superset-frontend
      cp -r ./superset ${{targets.destdir}}/app/
      cp setup.py MANIFEST.in README.md ${{targets.destdir}}/app/
      cp superset-frontend/package.json ${{targets.destdir}}/app/superset-frontend/

update:
  enabled: true
  ignore-regex-patterns:
    - '^superset-helm-chart'
    - 'rc\d+$'
  github:
    identifier: apache/superset
    use-tag: true

test:
  environment:
    contents:
      packages:
        - wolfi-base
        - superset
  pipeline:
    - runs: |
        export PATH=/usr/share/superset/venv/bin:$PATH
        export SUPERSET_SECRET_KEY="$(openssl rand -base64 42)"
        superset --help
