package:
  name: talloc
  version: 2.4.2
  epoch: 0
  description: Memory pool management library
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - docbook-xml
      - libxslt
      - python3-dev

pipeline:
  - uses: fetch
    with:
      expected-sha512: fb91665ffbe0cce96b1359940ff3ed21330c81c5331140788a26aa94f82b50492176e6000ff54b31d1a434bb1cb53a6a2c7894153545252a1fd91bda7c05a213
      uri: https://samba.org/ftp/talloc/talloc-${{package.version}}.tar.gz

  - uses: autoconf/configure
    with:
      opts: |
        --bundled-libraries=NONE \
        --builtin-libraries=replace \
        --disable-rpath \
        --disable-rpath-install \
        --without-gettext

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: talloc-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - talloc

  - name: "talloc-doc"
    description: "talloc documentation"
    pipeline:
      - uses: split/manpages

  - name: "py3-talloc"
    description: "Python 3 binding for libtalloc"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libpy* "${{targets.contextdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/python3* "${{targets.contextdir}}"/usr/lib

update:
  enabled: true
  release-monitor:
    identifier: 1733
