package:
  name: tcl-tls
  version: 1.7.22
  epoch: 0
  description: OpenSSL extension to Tcl
  copyright:
    - license: TCL
  dependencies:
    runtime:
      - tcl

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssl-dev
      - tcl-dev

pipeline:
  - uses: fetch
    with:
      uri: https://core.tcl.tk/tcltls/uv/tcltls-${{package.version}}.tar.gz
      expected-sha512: 28c76a6e7333b6ed1d83234691d61c9e71a59d0a6a28182fc0f50e97cae7b54da63ac76527e3b16087f3eab0b9cfe19bad02362e485d0cf378724de534805e99

  - uses: autoconf/configure
    with:
      opts: |
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        --enable-shared \
        --with-ssl-dir=/usr

  - uses: autoconf/make

  - runs: |
      make DESTDIR="${{targets.destdir}}" install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 7568
