package:
  name: tevent
  version: 0.16.1
  epoch: 0
  description: The tevent library
  copyright:
    - license: LGPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmocka-dev
      - libtirpc-dev
      - python3-dev
      - talloc-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 362971e0f32dc1905f6fe4736319c4b8348c22dc85aa6c3f690a28efe548029e
      uri: https://samba.org/ftp/tevent/tevent-${{package.version}}.tar.gz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: tevent-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - tevent
    description: tevent dev

  - name: py3-tevent
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/python3* "${{targets.contextdir}}"/usr/lib
    description: Python 3 binding for the tevent library

update:
  enabled: true
  release-monitor:
    identifier: 1736
