package:
  name: trafficserver-9
  version: 9.2.4
  epoch: 2
  description: Apache Traffic Server™ is a fast, scalable and extensible HTTP/1.1 and HTTP/2 compliant caching proxy server.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - linux-headers
      - openssl-dev
      - pcre-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 90fbf13db0858cef0e0a094f445d846b60a4c1ef
      repository: https://github.com/apache/trafficserver
      tag: ${{package.version}}

  - runs: |
      autoreconf -if

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - rc*
  github:
    identifier: apache/trafficserver
    use-tag: true
    tag-filter-prefix: 9.

test:
  pipeline:
    - runs: |
        traffic_server --version
        traffic_cache_tool --help
        traffic_crashlog --version
        traffic_ctl --version
        traffic_ctl --help
        traffic_layout --version
        traffic_layout --help
        traffic_logcat --version
        traffic_logstats --version
        traffic_manager --version
        traffic_via --version
    - uses: test/pkgconf
