package:
  name: valijson
  version: 1.0.3
  epoch: 1
  description: "C++ library for validating JSON schema"
  copyright:
    - license: "BSD-2-Clause"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cmake
      - openssf-compiler-options
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tristanpenman/valijson.git
      tag: v${{package.version}}
      expected-commit: fc9ddf14db683c9443c48ae3a6bf83e0ce3ad37c

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: valijson-static
    description: "C++ library for validating JSON - static libraries"
    pipeline:
      - uses: split/static

  - name: valijson-dev
    description: "C++ library for validating JSON - development headers"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: tristanpenman/valijson
    strip-prefix: v
