package:
  name: wasmcloud
  version: 1.3.1
  epoch: 0
  description: "wasmCloud allows for simple, secure, distributed application development using WebAssembly components and capability providers."
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wasmCloud/wasmCloud
      tag: v${{package.version}}
      expected-commit: f5e3e86fc2e9f0b94d59d84f7ce8b6b37cdf5a92

  - uses: rust/cargobump

  - name: Configure and build
    runs: |
      cargo auditable build --release --bin wasmcloud
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/wasmcloud ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: wasmCloud/wasmCloud
    strip-prefix: v
    tag-filter-prefix: v

test:
  pipeline:
    - name: Verify wasmcloud installation
      runs: |
        wasmcloud --version || exit 1
        wasmcloud --help
