package:
  name: wayland-protocols
  version: "1.38"
  epoch: 0
  description: Protocols and protocol extensions complementing the Wayland core protocol
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - meson
      - python3-dev
      - wayland-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: ff17292c05159d2b20ce6cacfe42d7e31a28198fa1429a769b03af7c38581dbe
      uri: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/${{package.version}}/downloads/wayland-protocols-${{package.version}}.tar.xz

  - runs: |
      env
      meson . output --prefix=/usr
      meson compile -j $(nproc) -C output

  - uses: meson/install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 13997
