package:
  name: xtrans
  version: 1.5.1
  epoch: 0
  description: X transport library
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssf-compiler-options
      - util-macros
      - xmlto

pipeline:
  - uses: fetch
    with:
      expected-sha256: dea80fbd8c3c941495b4b1d2785cb652815d016849a0d2ef90d1140de916993e
      uri: https://www.x.org/releases/individual/lib/xtrans-${{package.version}}.tar.xz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 13440
