package:
  name: zetasql
  version: 2024.06.1
  epoch: 1
  description: ZetaSQL - Analyzer Framework for SQL
  copyright:
    - license: Apache-2.0
  resources:
    cpu: 33
    memory: 100Gi

environment:
  contents:
    packages:
      - bash
      - bazel-6
      - binutils
      - build-base
      - busybox
      - ca-certificates-bundle
      - gcc-12
      - git
      - openjdk-17
      - openjdk-17-default-jvm
      - patch
      - python3
      - tzdata
      - wolfi-baselayout
  environment:
    BAZEL_ARGS: "--config=g++"
    EXTRA_BAZEL_ARGS: "--tool_java_runtime_version=local_jdk"
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/google/zetasql
      tag: ${{package.version}}
      expected-commit: f6df6971a205790966e73eda0134f05a022d0e6a

  - uses: patch
    with:
      patches: multi-arch-for-linux.patch

  - runs: |
      cd zetasql
      bazel build --verbose_failures ${BAZEL_ARGS} $EXTRA_BAZEL_ARGS -c opt ...
      # TODO need to copy whats required after this from either bazel-bin or bazel-out

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - zetasql

update:
  enabled: true
  github:
    identifier: google/zetasql
    use-tag: true
