issuer: https://accounts.google.com

# staging-images: not in use
# prod-images: bot-gpt@prod-images-c6e5.iam.gserviceaccount.com
subject: "113866670232979663129"

permissions:
  contents: read
  pull_requests: write