issuer: https://accounts.google.com

# have more than one service account
# staging-images: not in use
# prod-images: bot-label-sla@prod-images-c6e5.iam.gserviceaccount.com (102019613950547524864)
# prod-images: cron-sla-label@prod-images-c6e5.iam.gserviceaccount.com (102992167601221151705)
subject_pattern: "(102019613950547524864|102992167601221151705)"

permissions:
  contents: read
  pull_requests: write # to add labels
