issuer: https://accounts.google.com

# prod-images: approver-pr-sa@prod-images-c6e5.iam.gserviceaccount.com
subject: "111142206721819985077"

permissions:
  contents: write
  actions: read
  checks: read
  pull_requests: write
