issuer: https://accounts.google.com

# prod-images: bot-bincapz-check@prod-images-c6e5.iam.gserviceaccount.com
subject: "100391373612188354572"

permissions:
  contents: read
  actions: read
  checks: read
  pull_requests: write
